### ISSUE TITLE
[BUG]Parentheses in name of Content broke admin-ui

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#1001]
# 🐜 Bug Report

If Name of Content contains parentheses, the Content is unavailable on some actions

## 📦 Package / Application

admin-ui
## 📃 Version

latest

## 🐜 Describe the bug

admin-ui actions runs 404 if Name contains parenthesis

## 👉 Steps To Reproduce

1. Create a Content with parentheses, dor example a movie title: "Run (1991)"
2. Navigate on the newly created Content or try to Edit

## 😯 Current behavior

Browse it will show a "Cannot find path" error message. Edit will lead to an empty page, Network tab shows 404.

## 🤔 Expected behavior

Expected to works like charm

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/17780970/95121260-1620ef00-074f-11eb-9012-3d2414db89e9.png)

![image](https://user-images.githubusercontent.com/17780970/95121400-48325100-074f-11eb-8eff-a27c6729387e.png)

## 🌍 Your environment (for apps / examples)

- Device:
  PC
- OS:
  Windows 10
- Browser:
  Edge
- Version:
  latest

**Comment by herflis** [comment]
Related to [this](https://github.com/SenseNet/sn-client/pull/949) so I move this to review
