### ISSUE TITLE
[BUG] scroll bar anomaly on profile page my invoices panel

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1029]
# 🐜 Bug Report

On profile page my invoices tab when the sort by panel is opened the scroll bar disappears from the window.

After closing, the scroll bar comes back.

## 🖼 Screenshots

![](https://trello-attachments.s3.amazonaws.com/5f0ee3deae96672f6b9d8ee3/5f47b47e99e556897685342a/a2637bde12d2ffb91891006764a94b91/image.png)

![](https://trello-attachments.s3.amazonaws.com/5f47b47e99e556897685342a/581x1079/0e551abb0102a1bfe7120a2f6ea823ff/image.png)

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/102
