### ISSUE TITLE
[BUG] false cancel status on profile page

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1031]
# 🐜 Bug Report

I've noticed that my basically fresh repo says that it is already cancelled on the change plan screen, current plan section

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/19875603/96612767-76429400-12fe-11eb-9c7d-8f532606b064.png)

**Comment by herflis** [comment]
[https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/93?_a=overview](https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/93?_a=overview)
