### ISSUE TITLE
[FEATURE] Repo order on profile page

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1033]
# 🙋 Feature Request

I've noticed that there is some strange order logic on profile page my repos section.
Once the display name of a repo is modified it's pushed down at the very bottom after a page refresh. 

## 😯 Current Behavior

video capture here:
https://1drv.ms/v/s!AkVGGwEsXFv7gspq4MpnewyeQSqLVA?e=5n3d0J

## 💁 Possible Solution

A more predictable and permanent order logic could be better, like creation date. That way, the order of my repos would "never change".

**Comment by pusztaienike** [comment]
Fix: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/97?_a=overview
