### ISSUE TITLE
[FEATURE] open individual invoice

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1035]
# 🙋 Feature Request

It should be possible to open a single invoice by clicking on the invoice number on profile page my invoices section.

![image](https://user-images.githubusercontent.com/19875603/96738943-8a01ff00-13bf-11eb-8234-0afc761b9edf.png)

## 💁 Possible Solution

acceptance criteria:
- every invoice number should be clickable
- when clicked the invoice summary page should open
- invoice number should be underlined @hover

**Related issue:**
https://github.com/SenseNet/sn-client/issues/772

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/130?_a=overview
