### ISSUE TITLE
[BUG] TreeView level overlay

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1039]
# 🐜 Bug Report

When I open a level in the TreeView the main level's next items slip on the opened child level. The screenshot shows the bug.

## 👉 Steps To Reproduce

1 - Log in to https://admin.test.sensenet.com repo: https://snover.service.sensenet.com.
2 - In the tree click (open) the explorer (last item) / Content / Smartfolders
3 - Scroll down

## 🖼 Screenshots

![3-treeview-linespaces](https://user-images.githubusercontent.com/2006057/97058564-75279600-158e-11eb-8cb6-eb4af89622c6.png)

## 🌍 Your environment (for apps / examples)

- Browser:
Chrome 1392x984
- Version:
86.0.4240.75

**Comment by herflis** [comment]
@kavics I cannot reproduce this issue after the upgrade, can you please confirm, that the issue is gone?
![image](https://user-images.githubusercontent.com/6968860/97270872-1da85500-1830-11eb-8dd1-9a473d0dcbc0.png)
