### ISSUE TITLE
[BUG] Rendering errors on SETUP page

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1040]
# 🐜 Bug Report

There are more rendering errors on the Setup page.
1 - Clipped titles: "DocumentPreview.settin",  "TaskManagement.settin"
2 - Invisible and multiline buttons.

## 👉 Steps To Reproduce

1 - Log in to https://admin.test.sensenet.com repo: https://snover.service.sensenet.com.
2 - In the left menu click Setup.
3 - See the boxes (screenshot)

## 🤔 Expected behavior

1 - The titles should not be cropped.
2 - The buttons should be always visible.
3 - The space among the buttons should be proportional.
4 - A button should always be a single line.

## 🖼 Screenshots

![5-settings](https://user-images.githubusercontent.com/2006057/97060153-c76ab600-1592-11eb-9807-c509f10dbade.png)

## 🌍 Your environment (for apps / examples)

- Browser:
  Chrome
- Version:
  86.0.4240.75

**Comment by herflis** [comment]
@kavics I cannot reproduce this issue, can you please confirm that the issue is gone?

![image](https://user-images.githubusercontent.com/6968860/97271344-b9d25c00-1830-11eb-933e-8ffc474dec82.png)

**Comment by taki9** [comment]
On setup page height of boxes in a row should always be equal.
(setup.tsx line 95 should align items as stretch,
