### ISSUE TITLE
[BUG] Date control: unnecessary error indication

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1042]
# 🐜 Bug Report

The untouched Date component always shows an unnecessary error.

## 👉 Steps To Reproduce

1 - Log in to https://admin.test.sensenet.com repo: https://snover.service.sensenet.com.
2 - On the left menu click the globe.
3 - Select "Edit" from the Actions of the first line (PersionalSettings)
4 - See the screenshot.

## 😯 Current behavior

See the screenshot

## 🤔 Expected behavior

Untouched Date component should not show any errors.

## 🖼 Screenshots

![6-lifespan-off](https://user-images.githubusercontent.com/2006057/97061000-98a20f00-1595-11eb-82e7-54201c1f0bc0.png)

## 🌍 Your environment (for apps / examples)

- Browser:
Chrome
- Version:
86.0.4240.75

**Comment by herflis** [comment]
@kavics This issue was related with the DefaultValue of the DateTime fields which was fixed but cannot be fixed on existing content without update them one by one. So please check if it occurs when you are creating a new content and if not, then I think it is fixed.
