### ISSUE TITLE
[BUG] Default date

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1043]
# 🐜 Bug Report

Why was everyone born on the first of January?

## 👉 Steps To Reproduce

1 - Log in to https://admin.test.sensenet.com repo: https://snover.service.sensenet.com.
2 - On the left menu click Users and Groups.
3 - Click "snteam", double-click "Gyebi"
4 - See the screenshot.

## 🤔 Expected behavior

Untouched Date component should not show date and time which I did not enter.

## 🖼 Screenshots

![7-birthdate](https://user-images.githubusercontent.com/2006057/97061280-a1dfab80-1596-11eb-949c-0b846dd617f3.png)

## 🌍 Your environment (for apps / examples)

- Browser:
Chrome
- Version:
86.0.4240.75

**Comment by herflis** [comment]
@kavics Because this is the DefaultValue of the Birthday field
