### ISSUE TITLE
[BUG] Missing string resources

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1044]
# 🐜 Bug Report

Missing string resources.

## 👉 Steps To Reproduce

1 - Log in to https://admin.test.sensenet.com repo: https://snover.service.sensenet.com.
2 - On the left menu click Users and Groups.
3 - Click any user's Actions.
4 - See the screenshot.

## 🖼 Screenshots

![8-missing-strres](https://user-images.githubusercontent.com/2006057/97061499-61346200-1597-11eb-8370-ac4ce99b0a03.png)

**Comment by herflis** [comment]
@kavics it is fixed, please confirm that the issue is gone :)
