### ISSUE TITLE
[snaas] Registration page pimp-up

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1093]
![image](https://user-images.githubusercontent.com/6968860/100071668-986a8d00-2e3b-11eb-9367-a05a6480ad4a.png)

[register.zip](https://github.com/SenseNet/sn-client/files/5588569/register.zip)

**Comment by pusztaienike** [comment]
PR:
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver/pullrequest/101

![2020-11-27_13h40_51](https://user-images.githubusercontent.com/22347393/100451128-2900d180-30b7-11eb-9b10-8975cb132bc4.png)
![2020-11-27_13h41_25](https://user-images.githubusercontent.com/22347393/100451131-2a31fe80-30b7-11eb-9a78-e5b929543134.png)

Note: I have set the left column invisible on mobile view
