### ISSUE TITLE
[snaas-profile] User profile picture upload icon

### ISSUE THREAD

**Issue by taki9** [SenseNet/sn-client#1111]
# 🐜 Bug Report

The icon is behind the current avatar of the user.

## 🤔 Expected behavior

The icon should be above the avatar.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/8918642/103512745-9c8dbf80-4e69-11eb-92c0-88420d9da026.png)

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/119
