### ISSUE TITLE
[SNaaS profile] Enterprise plan

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1118]
Put the button and the dialog (and the related feature behind) back for requesting an enterprise plan. 

- [x] a new field should be added to the Task to contain info from the dialog (it is now ok, to put the whole information into one LongText)
- [x] add the value to the task creation request that is sent and save it to the field
- [x] we should use here the old task creator method, because this repo request and the actual repository assignment are not follow each other directly, there will be a multistep consultation between the sales and the customer

**Comment by pusztaienike** [comment]
PRs:
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/116
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-services/pullrequest/115
