### ISSUE TITLE
[BUG][@sensenet/react-controls] The OnChange method doesn't get fired for some controls during new action

### ISSUE THREAD

**Issue by LuisAverhoff** [SenseNet/sn-client#112]
# 🐜 Bug Report

The OnChange method in the @sensenet/react-controls package doesn't get fired for some controls during new action.

## 📦 Package / Application

@sensenet-react-controls(primarily the sn-dms-demo as that is where it is being used )

## 📃 Version

@sensenet/react-controls - 2.3.7
sn-dms-demo - 1.1.0

## 🐜 Describe the bug
I'm not sure if the entirely a bug or an oversight but I'm going to put it here any way. There are some controls such as this one  https://github.com/SenseNet/sn-client/blob/develop/packages/sn-controls-react/src/fieldcontrols/ShortText/ShortText.tsx that do not fire the onchange action if the case is a new action while https://github.com/SenseNet/sn-client/tree/develop/packages/sn-controls-react/src/fieldcontrols/DisplayName does. This is problematic if you have a custom content type that utilizes fields like short text or any other field that does not fire the onchange during a new action as those values will not get saved to the content repository when you click submit.

## 👉 Steps To Reproduce
1.) Create a custom content type definition in your local sensenet backend that utilizes the short text with visible true and all the visible properties set to show so that we can see what the value is when we go to edit.
2.) add that custom content type definition as an allowed child type for the document library.
3.) set the necessary permissions for alba to create this content.
4.) Login in the sn-dms-demo web app.
5.) Click the new button and you should see your content as one of the available content types that you can create
6.) Click on it, fill out the form and submit. The content should have been created in backend and should be visible in the content list.
7.) Go back to the backend and into alba's document library. You should see your newly create content there.
8.) Click on edit this content.
9.) The custom short text field is empty when it should be populated with the value that you entered in the form.

## 😯 Current behavior

The values that you set on the fields in the front end for some content type during a new action does not get saved in the backend because the OnChange method does not get fired.

## 🤔 Expected behavior

The values that you set on the fields in the front end for some content type during a new action should get saved in the backend.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) | ts
| Operating System | Windows 10
| NPM/Node/Yarn    | NPM
| Bundler          | Webpack

## 🌍 Your environment (for apps / examples)

- Device:  **Surface Tablet Pro 4**
- OS: **Windows 10**
- Browser: **Chrome**
- Version: **71.0.3578.98**

**Comment by herflis** [comment]
Hi Luis,

thanks for creating this issue. This bug is already fixed and the fix is merged into the develop branch. It will be the part of the next release which will be published in two weeks.

**Comment by LuisAverhoff** [comment]
@herflis Cool, before I make another make bug request pertaining the @sensenet/react-controls, did you guys fix the issue with the field being set to false every time the field is empty and you are editing a property of some sort? If not, I'll file that bug report too.

**Comment by LuisAverhoff** [comment]
@herflis Nevermind, I found the code segment that was doing that. Might want, want to have return an empty string instead of false. It is this method in the EditView.tsx module.

```
getFieldValue(name) {
        if (name && this.props.content[name]) {
            return this.props.content[name];
        }
        else {
            return '';
        }
    }
```

**Comment by B3zo0** [comment]
The fix is released in https://github.com/SenseNet/sn-client/releases/tag/%40sensenet%2Fcontrols-react%402.4.0
