### ISSUE TITLE
[FEATURE] SnaaSTasks should be permanently deleted on delete action

### ISSUE THREAD

**Issue by enikonemeth** [SenseNet/sn-client#1132]
# 🙋 Feature Request

I can't see the point of move SnaasTasks to trash. If a workflow has sucessfully finished we can delete the tasks permanently.

## 📦 Package / Application

admin-ui

**Comment by herflis** [comment]
I think it should be merged with the another issue (connected as a dependency)

**Comment by tusmester** [comment]
Closed as obsolete.
