### ISSUE TITLE
[BUG] Different icons for the same content type

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#1219]
# 🐜 Bug Report

I have found that we use different icons for the same content type. E.g: samle ws, image lib.
![image](https://user-images.githubusercontent.com/22347393/109624457-871dd480-7b3e-11eb-9167-f861e5441774.png)
We should check them and correct if needed

## 📦 Package / Application

admin-ui

**Comment by herflis** [comment]
related prs: 
[#147](https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-services/pullrequest/147?_a=overview)
[#1360](https://github.com/SenseNet/sensenet/pull/1360)
