### ISSUE TITLE
Headline text is not completely visible on registration page[BUG]

### ISSUE THREAD

**Issue by molnarm84** [SenseNet/sn-client#1253]
# 🐜 Bug Report

The second line of the headline text above the registration form is not completely visible on registration page.

## 🐜 Describe the bug

The second line of the headline text above the registration form is not completely visible on registration page.

## 😯 Current behavior

The second line of the headline text above the registration form is not completely visible on registration page.

## 🤔 Expected behavior

Text should be completely readable.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by herflis** [comment]
I close this issue because the registration screen is totally changed with #1303
