### ISSUE TITLE
Is there any library to work with sensenet and vue

### ISSUE THREAD

**Issue by rutup** [SenseNet/sn-client#1275]
Hi Team,
My Organization is having license of sensnet. I want to use sensenet  as PDF viewer with Vue js. Is there any library or nuget packege/ example for using it in Vue. Please share

**Comment by tusmester** [comment]
Hi @rutup, sorry for the late reply. Currently we are concentrating our efforts to the React library and have no Vue.js implementation. The only option I see is to take the react code and refactor it to a new library.
I'm closing this, but pls feel free to reopen if necessary.
