### ISSUE TITLE
[FEATURE] Allow user to connect to different DMS backend at login/register

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#128]
# 🙋 Feature Request

As a developer, I want to be able to define any DMS backend URL other than the default on the DMS login screen, mainly for debugging purposes.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.2.0

## 🤔 Expected Behavior

This function has to be available on the login screen, but since it will mainly be used by developers and not end users, it does not require too much focus.

Should be available on:
* [ ] Login screen
* [ ] Registration screen

## 😯 Current Behavior

Currently, we can only connect to the backend defined in the build.

## 💁 Possible Solution

Eg. a cogwheel or 3dots button next to the Login box, or maybe even better: just a link with an "Advanced settings" label, placed under the Sign in with Google button, popping up a window with the default URL that can be overwritten by the user.

## 🔦 Context

I want to check a feature or bug in two DMS backends and compare their behavior from the same DMS frontend.

**Comment by tusmester** [comment]
Closed as obsolete.
