### ISSUE TITLE
[snaas-profile] Clarify purpose of pages on the profile

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1285]
We got some feedbacks, that some of the pages on the profile are not clear for the users.

1. Documents page
- [x] We have to add a few sentence long intro about what this page is for
"Here you can see the terms of use (accepted during registration) and other related documents (contracts, purchase orders) if applicable."
- [x] we should check why the users do not see the terms of use in the document library

![image](https://user-images.githubusercontent.com/6968860/114666044-130a4b00-9cfe-11eb-9f8c-b5f0dea14429.png)

2. API keys
- [x] At the first login, when the user has no repositories yet, this page is empty, so the user does not know what is this for. We should display the text about api keys that is shown when the user has repositories and a button to get her/him to request a repository
Every fields should be visible (empty and disabled)

![image](https://user-images.githubusercontent.com/19875603/116056423-14ccfa80-a67e-11eb-84d8-2dd4b047c401.png)

current version:
![image](https://user-images.githubusercontent.com/6968860/114665991-fcfc8a80-9cfd-11eb-8344-c478c21f21fe.png)

**Comment by herflis** [comment]
[#185](https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/185) 
Empty doclib is a bug on the backend. I've made a separate issue for that,

**Comment by huszerlbence** [comment]
I've checked the changes on the test page and I think everything is okay except this part:
_we should check why the users do not see the terms of use in the document library_

I've logged in with a fresh account created a few days ago (sales@sensene.com) and I can't see the terms of use on the document tab.
