### ISSUE TITLE
[BUG] Different actions have the same parameters in the command palette

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1307]
# 🐜 Bug Report

There are cases when we have multiple actions with the same name but with different parameters, but the command palette returns always the same parameters no matter which action I want to use.

## 📦 Package / Application

@sensenet/sn-app

## 📃 Version

latest

## 🐜 Describe the bug

The command palette uses only the first action by name, even if there are several others with the same name

## 👉 Steps To Reproduce

1. Login to netcore test repo through admin.test.sensenet.com
2. Go to Settings and Open Webhooks
3. Create a sample WebHookSubscription if there are no items in the list.
4. Select an item in the webhook subscripion list
5. Hit Ctrl+Shift+P
6. Search for FireWebHook and choose the first one
7. Use Ctrl+shift to get the params
8. Close the dialog and try steps 4-7 with the second action

## 😯 Current behavior

Only path and eventType are the suggested parameters.

## 🤔 Expected behavior

The difference between the two actions is the id/path parameter, so one of them have the id param, the other one the path and the command palette should suggest the related parameters.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/6968860/116413299-c4999800-a837-11eb-8dea-a5e37d4f97d5.png)

![image](https://user-images.githubusercontent.com/6968860/116413765-340f8780-a838-11eb-8b79-1224e5fcbbae.png)

**Comment by tusmester** [comment]
Backend task for this: every operation should have a **unique identifier** to let the client keep track of actions by that id instead of name. 

##### Questions
- is it enough if we simply add this id to the schema? (`GetSchema` action)
- how long these ids should live? Is it a problem if we generate new ones every time when you request the schema?
- format? Is a GUID ok?
