### ISSUE TITLE
[BUG] Change which button is highlighted when reject/approve a content change

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1326]
We should clarify which button should be cliecked on the approve/reject dialog in the two modes.

## Current behavior
Approve is the primary and Reject is the secondary button which makes it confusing after filling the reject reason input.

![image](https://user-images.githubusercontent.com/6968860/120432220-e2e43d80-c379-11eb-8ef4-0130aa835287.png)

## Expected behavior
When the user chooses Reject first and the reject reason input becomes visible, the Reject button should become the primary button and aproove should become secondary.

![image](https://user-images.githubusercontent.com/6968860/120432582-6d2ca180-c37a-11eb-9f0a-7168e6836723.png)

**Comment by tusmester** [comment]
I could not reproduce this, reject reasons are visible to both businesscat and admin:
![image](https://user-images.githubusercontent.com/18169555/119456763-4a2b3d80-bd3b-11eb-93b6-b8ec0f911025.png)

### Suspicious thing
On the original screenshot the versions are not _Rejected_ but _Approved_ and _Pending_.
