### ISSUE TITLE
[FEATURE] modify registration confirm screen

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1336]
# 🙋 Feature Request

I would like to change the profile registration confirm screen to be more informative.

## 📦 Package / Application

sn over sn

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/19875603/119479860-5cb07180-bd51-11eb-83f7-d8a40c722845.png)

## 💁 Possible Solution

- [x] change big text to: Check your email to finish registration!
- [x] url should be removed

## 💻 Examples

![image](https://user-images.githubusercontent.com/19875603/119479899-676b0680-bd51-11eb-8004-9dc21587ba92.png)

**Comment by pusztaienike** [comment]
PR:
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver/pullrequest/194
Result:
![image](https://user-images.githubusercontent.com/22347393/120297607-8d505800-c2c9-11eb-9edf-60089951c341.png)
