### ISSUE TITLE
IS repo password screen

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1340]
There's a new screen in the registration and repository assignment process for providing password of the synced user. These page should have the same ui as the other IS pages. (this page could be reached if you register with a new user at [https://snaas-profile.test.sensenet.com/](https://snaas-profile.test.sensenet.com/) and there should be an assignable test repository as well)

The password input is required to fill! The form cannot be posted without validation

Now it is something like this:
![image](https://user-images.githubusercontent.com/6968860/119952466-57476700-bf9d-11eb-9967-ce3277ead0fe.png)

And it should look this way:
![image](https://user-images.githubusercontent.com/6968860/119954734-97a7e480-bf9f-11eb-9fbf-ccd134abf7b6.png)

**Comment by pusztaienike** [comment]
PR:
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver/pullrequest/194
Result:
![image](https://user-images.githubusercontent.com/22347393/120297496-6f82f300-c2c9-11eb-9f9b-cb51261c40a2.png)

**Comment by huszerlbence** [comment]
TEXT SUGGESTION:

Your sensenet repo is almost ready!

As a last step you need to provide a password for your repository admin user.
You'll be able log in with username: [username] and password you type below.
Once you repo is up and running you will receive a confirmation email.

**Comment by pusztaienike** [comment]
> TEXT SUGGESTION:
> 
> Your sensenet repo is almost ready!
> 
> As a last step you need to provide a password for your repository admin user.
> You'll be able log in with username: [username] and password you type below.
> Once you repo is up and running you will receive a confirmation email.

I made a little change: "Once you repo is up..." --> Once _your_ repo is up... , and it is DONE. ✔️ 

![image](https://user-images.githubusercontent.com/22347393/120493387-34f98300-c3bb-11eb-9b9d-cfe8b2f60e53.png)
