### ISSUE TITLE
Move gatsby starter to a separate repository

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1356]
[https://www.gatsbyjs.com/docs/creating-a-starter/](https://www.gatsbyjs.com/docs/creating-a-starter/)

- static: a directory for static assets, such as a favicon.ico file.
- .prettierrc (optional): a configuration file for Prettier, a JavaScript linter and formatter used for Gatsby development.
- LICENSE: a file containing an appropriate open source license, preferably with a BSD Zero Clause License.

Your starter should also have these qualities: 
- Available from a stable URL e.g.: gatsby new my-app https://github.com/gatsbyjs/gatsby-starter-blog
- Configurable 

Add your starter to the Gatsby Starter Library
- To make sure your starter is easily discoverable, you are welcome (but not required) to add it to the Gatsby Starter Library. Add tags to your starter by first checking for existing ones (like contentful, csv, etc.), and adding more if needed!

- Don't forget to update the documentation drafts by the changes

**Comment by pusztaienike** [comment]
PR: https://github.com/SenseNet/gatsby-starter-sensenet-blog/pull/1
