### ISSUE TITLE
AdminUI crashes on contents with parenthesis in their names

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#1370]
repro:
- eg. create a folder with a name "test (1234)"
- click on the newly created content -> crashes!

popup:
An error occured and your request couldn't be completed.
TypeError: Cannot read property 'replace' of undefined at https://admin.test.sensenet.com/static/js/main.d067b5d8.js:1:2452 at Array.map (<anonymous>) at Breadcrumbs_Breadcrumbs (https://admin.test.sensenet.com/static/js/main.d067b5d8.js:1:2247) at oh (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1868515) at di (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1878139) at gl (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1919752) at Qj (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1910594) at Kj (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1910517) at yj (https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1907328) at https://admin.test.sensenet.com/static/js/131.b3b6ac6b.js:2:1854575
Error message: Cannot read property 'replace' of undefined

**Comment by VargaJoe** [comment]
custom react app from sensenet core package is also affected

**Comment by VargaJoe** [comment]
sensenet client has the same problem when creating react app with it and try to use content.load()

a workaround to encode parenthesis "(" to "%28" and  ")" to "%29" in the path with idOrPath

**Comment by tusmester** [comment]
Hey @Restobit I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/sn-team-58d3e1e42f9a23ee7fc47ed7/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
