### ISSUE TITLE
Standalone repository: cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#1372]
After logging in to a standalone repository (without snover), the welcome (dashboard) page is empty, and navigation does not work.

### Main page
![image.png](https://images.zenhubusercontent.com/58e4ccee51aa2c30577a6f45/3084bd22-b2db-4527-a1eb-55f261975067)

### /custom/explorer/root
Note the double quotes in the list (missing display name?).
![image](https://user-images.githubusercontent.com/18169555/124611293-95c02380-de71-11eb-8d87-f4fdaf0e0a90.png)

**Comment by tusmester** [comment]
This will - hopefully - be fixed by #1544.

**Comment by pusztaienike** [comment]
Solved by: [1544](https://github.com/SenseNet/sensenet/issues/1544)
