### ISSUE TITLE
[BUG] Description column missing

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#138]
# 🐜 Bug Report

Description column is missing from grids showing group items

## 📦 Package / Application

sn-dms-demo

## 📃 Version

1.2.0

## 🐜 Describe the bug

When I click the Groups menu item and browse to see a list of groups, the Description column is missing from the grid.

## 👉 Steps To Reproduce

1. Log in to https://sn-dms-demo-dev.netlify.com/
1. Click Goups on the left menu
1. Double click Users and Groups, then Builtin, then Portal.
1. Description column is missing from the grid that appears.

## 😯 Current behavior

Description is missing

## 🤔 Expected behavior

Description should be present between Group name and Global/Local columns.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/55094653-16025680-50b7-11e9-995a-a53a709e9df9.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar I've fixed this in the branch for the group-page, so you can check it [here](https://deploy-preview-137--sn-dms-demo-dev.netlify.com)
