### ISSUE TITLE
Wrong PAT whit SN admin

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#1389]
UI shows the wrong PAT when logged in with sn admin.

**Comment by tusmester** [comment]
Pls add more details @VargaJoe , how to reproduce the issue, with which repo and user?

**Comment by VargaJoe** [comment]
logged in with sensenet (built in) admin I see the same token and secret as the repo owner (public admin) isntead a separate token with elevated permissions of the sensenet admin user

**Comment by tusmester** [comment]
Currently this is by design. We plan to revisit the security GUI and show more details later.
