### ISSUE TITLE
[BUG] Description field missing from group edit properties

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#139]
# 🐜 Bug Report

Description field missing from group edit properties

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

When the user edits the properties of a group item, the description field should be also editable, but it is not seen in the window.

## 👉 Steps To Reproduce

1. Log in to https://sn-dms-demo-dev.netlify.com/
1. Click Goups on the left menu
1. Double click Users and Groups, then Builtin, then Portal.
1. Right click any of the groups items, and click Edit
1. Edit properties window pops up, but Description field is not found there.

## 😯 Current behavior

The field is missing from the dialogue window

## 🤔 Expected behavior

The field should be there under the Group name field, above the Members references.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/55095285-2ff06900-50b8-11e9-833d-f001ec08ff58.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar I've fixed this in the branch for the group-page, so you can check it [here](https://deploy-preview-137--sn-dms-demo-dev.netlify.com)

**Comment by kultsar** [comment]
Seems good.
