### ISSUE TITLE
[BUG] Group related context actions should only be available on group items

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#140]
# 🐜 Bug Report

Group related actions (that appear in context menu for content items under the Groups menu) should be available only on group items.

## 📦 Package / Application

sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

Group related context actions appear on almost every content item (e.g. folders) that can be found in the Groups menu. Currently, they are Edit and Rename.

## 👉 Steps To Reproduce

1. Click Groups menu
1. Right click any content item that appears in any of the grids (except the ones that appear as default in the local root, so you will have to browse deeper in the hierarchy).

## 😯 Current behavior

Group related context actions appear on non group content items.

## 🤔 Expected behavior

Group related context actions should be available only on group content items

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/55096369-089a9b80-50ba-11e9-9e43-bfa517fb974d.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar I've fixed this in the branch for the group-page, so you can check it [here](https://deploy-preview-137--sn-dms-demo-dev.netlify.com)

**Comment by kultsar** [comment]
Seems good.
