### ISSUE TITLE
[BUG] Default and user sorted ordering in group related grids

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#141]
# 🐜 Bug Report

Default and non-default (user sorted) ordering in group related grids list items by modification time (ascending, items modified latest at the bottom).

## 📦 Package / Application

sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

Items in group related grids are ordered by ascending modification time. This is the default ordering, but if user tries to sorts items in a different way by clicking on sortable column headers, the ordering stays the same.

## 👉 Steps To Reproduce

1. Open any grid that displays groups under the Groups menu
1. Observe and contemplate on the ordering
1. Try to apply any other different sorting (click a few times on the Group name header)
Nothing changes so far
1. Now modify content items (eg. edit properties.
1. Modified item goes to the end of the list
1. Modify other items, and watch them go to the end of the list

## 😯 Current behavior

Ordering always lists items by ascending modification time.

## 🤔 Expected behavior

- [x] default ordering should list items by Group name (alfanumeric...?)
- [ ] user sorted lists should follow their own specific intended ordering (this means Group name alfanumeric ascending and descending, depending on the arrow in the column header).

## 🖼 Screenshots
![image](https://user-images.githubusercontent.com/39081660/55099864-ca54aa80-50c0-11e9-857e-94ade13b00e9.png)
![image](https://user-images.githubusercontent.com/39081660/55099875-d3de1280-50c0-11e9-8670-99beb45509e4.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar Ordering by DisplayName does not work now for items that have a localized DisplayName value. I've made [another issue for the backend](https://github.com/sensenet/sensenet/issues/603) about that because it is related with querying and can be experienced even on the old admin ui.

**Comment by tusmester** [comment]
Closed as obsolete.
