### ISSUE TITLE
[BUG] Rename action not doing anything

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#142]
Rename action in group related context menu actions does not seem to do anything.

# 🐜 Bug Report

When the user wants to rename a group with the Rename action, nothing happens.

## 📦 Package / Application

sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

Rename action does not seem to do anything when user starts it to rename a group.

## 👉 Steps To Reproduce

1. Open a groups grid in DMS Demo
1. Right click a group
1. Select Rename

## 😯 Current behavior

Nothing seems to happen

## 🤔 Expected behavior

A popup dialogue should open in which I can rename the group.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/55159113-ab0d5a00-5160-11e9-962d-2e129d8a852f.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check the fix in [this pr](https://github.com/SenseNet/sn-client/pull/165)
