### ISSUE TITLE
[BUG] Calendar event creation with default start and end dates

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#1429]
Calendar event creation failes because the default start date is missing from the request body if only the end date is written. This should not be a problem, the event should save correctly even if only one of the dates are provided.

The Start and End date default value should be the current date and time.

![image.png](https://images.zenhubusercontent.com/58e4d2b951aa2c30577a6fb6/dfbb574e-d230-4a4b-a435-78bc5c85d4f8)

The request body:
`{"EventType":["Deadline"],"EndDate":"2022-08-24T04:00:00.000Z","__ContentType":"CalendarEvent","__ContentTemplate":"CalendarEvent"}
`

**Comment by tusmester** [comment]
The start/end default value is set correctly in the CTD already.
