### ISSUE TITLE
[BUG] Reference picker: cannot enter parent directory

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#143]
# 🐜 Bug Report

User cannot enter parent directory when browsing directories with reference picker.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

User tries to browse to a reference in reference picker. User can enter subdirectories, but not parent directories.

## 👉 Steps To Reproduce

1. Click Groups in Left menu
1. Navigate to a group
1. Right click a group item and select the Edit action.
1. Click Add reference
1. Double click subdirectories and go deeper in the dir structure. At each level try to go back to the parent folder.

## 😯 Current behavior

User can not enter parent folders.

## 🤔 Expected behavior

User should be able to enter parent folders.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/55159700-f5430b00-5161-11e9-9214-702f38181b86.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar Did you try to doubleclick on it? Because it is working in the same way as the navigation into the folders.

**Comment by kultsar** [comment]
Yes, tried, does not work with double click. Simply cannot go up to parent.

**Comment by kultsar** [comment]
Had a look in Firefox, the same result, cannot enter parent directory.

- Device: laptop
  
- OS: Windows 10
  
- Browser: Firefox Quantum
  
- Version: 66.0.2 (64-bit)

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin UI 1.0](https://trello.com/c/db78sCs9/3-admin-ui-10)
