### ISSUE TITLE
[BUG] Left menu modifications

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#149]
# 🐜 Bug Report

Some modifications should be done in the left menu

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

When using a mobile device or Chrome with developer tools emulating a mobile device:
* Profile menu does not work. When the user clicks it, nothing happens.
* Settings menu should be removed. It makes sense only in desktop view.

Both mobile and desktop views:
* Normal workspace users should not see Users and Groups menu items.

Desktop view:
* Normal workspace users should not see Content Types and Content Templates menu items and submenu items.

## 👉 Steps To Reproduce

Sign in to DMS with the browser in mobile device or emulated mobile device and also in desktop view, and check the above menu items.

## 😯 Current behavior

See above

## 🤔 Expected behavior

See above

## 🖼 Screenshots

Pls, let me know if I should add screenshots for the above variations.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by herflis** [comment]
@kultsar check [this pr](https://github.com/SenseNet/sn-client/pull/165) for the fix
for the profile link, settings is here for the user edit not for the .settings files and it comes from the usermenu as the link for the profile and logout
