### ISSUE TITLE
[BUG] Image upload problems in avatar picker

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#150]
# 🐜 Bug Report

I have various problems with the image upload when used in the avatar picker, eg: image is not uploaded, or uploaded to the wrong folder. Sometimes can reproduce, sometimes cannot. 

## 📦 Package / Application

sn-dms-demo

## 📃 Version
1.2.0

## 🐜 Describe the bug

Note: we might want to wait for this enhancement first: https://github.com/SenseNet/sn-client/issues/125

I have various problems with the image upload when used in the avatar picker. Sometimes can reproduce, sometimes cannot.

* Often the image does not upload at all, it does not appear in the folder even after closing the dialogue and reopening it. At the moment it always happens (even after logging out and logging back in), but half an hour ago just sometimes.
* Sometimes image uploads to the folder I switch to after the upload (upload, switch to another folder, image uploads here)

## 👉 Steps To Reproduce

1. Click Profile menu  / Settings
1. Open avatar picker (Add or Change avatar button)
1. Upload an image.
  * Image might not be uploaded. Can reproduce this _now_ every time.
  * Image might sometimes be uploaded to the wrong folder. Eg. Switch to another folder, close avatar picker, come back, and image is in the folder that you switched to after the upload was initiated. Cannot reproduce this now.

## 😯 Current behavior

* Image not always uploaded
* sometimes uploaded to the folder different from the one where the upload was initiated.

## 🤔 Expected behavior

* Image should be uploaded
* to the folder where upload was initiated

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar pls check if one of the mentioned issues still remain [here](https://github.com/SenseNet/sn-client/pull/165)
