### ISSUE TITLE
[FEATURE] Refresh user page after submitting changes

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#151]
# 🙋 Feature Request

We should refresh the user page after editing user and submitting changes. 

## 📦 Package / Application

sn-dms-demo

## 📃 Version

1.2.0

## 🤔 Expected Behavior

After initiating an edit action, dialogue should always contain fresh data. Since this is an example app, we need to discuss an optimal solution

* refresh after submit is enough?
* read fresh data from backend when opening the edit dialogue?
* do we lock the content while editing?

## 😯 Current Behavior

1. Admin (or anybody with permission) edits user
1. Makes and submits changes
1. Admin - without refreshing the edited user - edits user again. Will see unmodified data in the dialogue. If the admin makes different changes and clicks submit, will lose changes made in the previous step.

**Comment by herflis** [comment]
@kultsar check the fix in [this pr](https://github.com/SenseNet/sn-client/pull/165)

**Comment by kultsar** [comment]
@herflis, it still behaves the same for me, but I just realized it does not only apply to users but probably to any content. I think we should close this issue and I will create a new one and we should discuss.

**Comment by kultsar** [comment]
@herflis Sorry, I must correct myself, the fix works for me also. But I will still create that other issue.
