### ISSUE TITLE
The list of user groups is not fully scrollable to the bottom

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#1535]
Currently, there is an issue with the user groups interface, where the list fails to scroll completely to the bottom. As a result, the last element in the user groups list is not visible, making it inaccessible for users. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d9201102bc412151d49510c136a0e7dbf7e185b/image.png)

**Comment by tusmester** [comment]
Related to the following issues:
https://github.com/SenseNet/sensenet/issues/2004
https://github.com/SenseNet/sn-client/issues/1587
