### ISSUE TITLE
Incorrect title of integer field

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#1552]
There is a display issue when attempting to edit one of the fields on the Webhook editor page. The presentation of the percentage field editing is incorrect.

- [ ] fix field title
- [ ] hide Successful % field from Edit view

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad1c38d1636b645c9bc3c4acfca228b4d089157/image.png)

**Comment by marosvolgyiz** [comment]
még nincs javítva, reprodukció: 
hosszú a field displayname-je.
