### ISSUE TITLE
Content name in the tree

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#1590]
Currently we display the content display name in the grid. How can we show the name as well, so that developers can have a better understanding of where they are in the tree?

TODOS:
1. simply replace display name with Name in the tree (CON: there may be certain content types where this is not wanted - e.g. autogenerated names like MyContent-1, MyContent-2)
2. tooltip on hover
3. Use ... in the middle of the word when the length is to long (UX solution macOS)
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3l4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--373038842adf180d8efb1267c70ddc062a5f3133/image.png" alt="image.png" />

**Comment by marosvolgyiz** [comment]
https://copyprogramming.com/howto/ellipsis-in-the-middle-of-a-text-mac-style
