### ISSUE TITLE
Compact view to display more info on the screen

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#1592]
Let's discuss the amount of white space on admin UI. 
full screen 1920x1080px 100% font scalling 0%scroll
- height of rows in the grid: 25 
- height of the top row: 35
Compact areas:
- Top menu
- grid header
- breadcrumb 

![image](https://github.com/SenseNet/sn-client/assets/18169555/ab99917a-1631-494f-852c-aca10dbc9d96)

**Comment by marosvolgyiz** [comment]
- Breadcrumb jobban összehúzni
- system settingsnél más a betűméret mint a breadcrumbnál. és nem ugyan annyi a behúzás

**Comment by marosvolgyiz** [comment]
- Breadcrumb jobban összehúzni
- system settingsnél más a betűméret mint a breadcrumbnál. és nem ugyan annyi a behúzás

**Comment by marosvolgyiz** [comment]
- icon és name közötti távolság a tree-ben legyen kisebb.

**Comment by marosvolgyiz** [comment]
User edit nézetében a gombok lelógnak
