### ISSUE TITLE
Hide Settings folders in the grid

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#1594]
Currently when there is a local setting folder (e.g. because of a custom grid column config) we see it in the grid. These should be hidden as they are not intended to be managed by user - or at least not frequently.

Find a way to hide the Settings folders but still let power users access them when necessary - e.g. when editing a custom local setting.

- Only in the grid, or in the tree as well? - everywhere
- Display a switch on the UI to show these system contents.

![image](https://github.com/SenseNet/sn-client/assets/18169555/5b71bb46-30d3-4b06-ac3c-4960691d23eb)

**Comment by marosvolgyiz** [comment]
<img width="1910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e493bd95fb60eebc8861bfaceba891d70e171f41/image.png" alt="image.png" />

**Comment by marosvolgyiz** [comment]
<img width="431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e34d24d155b1f54bb29fba65946f5f77738920f/image.png" alt="image.png" />

**Comment by marosvolgyiz** [comment]
Save all data to user settings. 
Title: View options
Items: 
- Visible Hiddens items (default false) 
- Dark Theme
- Visible DisplayName in Tree (default false, not part of this story)
