### ISSUE TITLE
[BUG] [more tests needed before fix] New content created in global workspace - various results

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#160]
# 🐜 Bug Report

Needs more tests before fixing. So far I found that when I want to create new content in a global workspace, the following happened:
* Folders were created in user's private workspace.
* Images were created sometimes in the correct workspace, sometimes in the private one
* Other new contents were not created at all

## 📦 Package / Application

sn-dms-demo

## 📃 Version

1.3.1

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by tusmester** [comment]
Closed as obsolete.
