### ISSUE TITLE
[BUG] ListPicker reloads always the initial parent and items

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#166]
# 🐜 Bug Report

ListPicker reloads always the initial parent/content item list even if we did something on a lower level (e.g. uploding a content)

## 📦 Package / Application

@sensenet/pickers-react

## 📃 Version

1.0.2

## 🐜 Describe the bug

ListPicker reloads always the initial parent/content item list even if we did something on a lower level (e.g. uploding a content)

## 👉 Steps To Reproduce

1. Login to dms with businesscat
2. Navigate to a user profile with link in the usermenu
3. Edit user
4. Open the avatar picker
5. Open demoavatars folder 
6. Upload an img 

## 😯 Current behavior

Image uploaded successfully and the content of the picker reloads but not the current level but the initial one (parent folder of the demoavatars)

## 🤔 Expected behavior

Picker should reload the current folder (demoavatars)

**Comment by kultsar** [comment]
👍
