### ISSUE TITLE
[BUG] Default ordering cannot be changed

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#168]
Similar to #141, the user cannot change the ordering of user list related grids.

# 🐜 Bug Report

Sorting cannot change the default ordering of any grid related to user lists (including the Builtin and Public folders).

## 📦 Package / Application

sn-dms-demo
## 📃 Version
1.3.1

## 🐜 Describe the bug

Sorting cannot change the default ordering of any grid related to user lists (including the Builtin and Public folders).

## 👉 Steps To Reproduce

1. Go to _Users_ in the left menu
1. Stay in the grid you find, or open subfolders
1. Try to sort the grid in a different way from default ordering (click any clickable column headers)

## 😯 Current behavior

Ordering should change.

## 🤔 Expected behavior

Ordering does not change. 

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check [this pr](https://github.com/SenseNet/sn-client/pull/165) for the fix
