### ISSUE TITLE
[BUG] Newly added user cannot log in

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#169]
# 🐜 Bug Report

DMS Admin adds a new user to the system, but the new user cannot log in.

## 📦 Package / Application

sn-dms-demo
## 📃 Version
1.3.1

## 🐜 Describe the bug
DMS Admin adds a new user to the system, but the new user cannot log in.

## 👉 Steps To Reproduce
1. Log in as a DMS admin (businesscat)
1. Click Users in the left menu
1. Open BuiltIn or Public
1. Click +New user
1. Fill in (click enable also) and save the new user 
1. Log out and try to log in with the new user

## 😯 Current behavior

The new user cannot log in.

## 🤔 Expected behavior
The new user should be able to log in.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by pusztaienike** [comment]
@kultsar: Are you still working on this issue?
