### ISSUE TITLE
[BUG] Adding new user fails or succeeds with wrong (group) username

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#173]
# 🐜 Bug Report
User cannot be added to DMS, or in certain cases can be added, but with a wrong username.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.3.1

## 🐜 Describe the bug

Users cannot be added to DMS by default, they are just not saved. However, if I added a new group before, then the system remembers the name, then the user is saved, and the username field will receive the group name value. (Please note, a few days ago users could be saved without adding a group, then users were saved with usernames something like "Username-20180422").

## 👉 Steps To Reproduce

Case A, user not saved:
1. Go to Users / Users and Groups / Public
1. Click +New user
1. Enter all required fields
1. Click Submit

Case B, user saved with newly added group's name:
1. Go to Groups / Users and Groups / BuiltIn / Portal
1. Add a new group, with name eg. "Groupname"
1. Go to Users / Users and Groups / Public
1. Click +New user
1. Enter all required fields
1. Click Submit

## 😯 Current behavior
* Case A: User is not created
* Case B: User with "Groupname" is created

## 🤔 Expected behavior
* Case A: User should be created with name given in User name field
* Case A: User should be created with name given in User name field

At present we do not have a User name field in the New user window. We need to add it, I think.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by pusztaienike** [comment]
@kultsar: Are you still working on this issue?
