### ISSUE TITLE
[BUG] Cannot log in with newly created user (invalid salt)

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#174]
# 🐜 Bug Report
Probably related to #173

Cannot log in with newly created user.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.3.1

## 🐜 Describe the bug

Cannot log in to DMS with newly created user, I get "Wrong user name or password" message from the system.

## 👉 Steps To Reproduce

1. Create user on DMS UI. (See also #173)

Case A: Try logging in on DMS UI
1. Open DMS with unauthenticated (logged out) user.
1. Enter e-mail address and corresponding password for newly created user.

Case B: Trying to log in with the old (webpages) UI
1. Open the old UI with unauthenticated (logged out) user.
1. Enter e-mail address and corresponding password for newly created user.

## 😯 Current behavior
* Case A, DMS UI: Cannot log in, getting "Wrong user name or password" error. Accoring to DevTools backend says 401, "You do not have permission to view this directory or page."
* Case B, old webpages UI: Cannot log in, get error message:

```
An unexpected error occurred, please report the following technical details to your system
Exception type: System.ArgumentException
Exception message:

Invalid salt <br />Parameter name: salt
```

## 🤔 Expected behavior

User should be able to log in.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by pusztaienike** [comment]
@kultsar: Are you still working on this issue?
