### ISSUE TITLE
[BUG] Cannot see/edit user pages

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#175]
# 🐜 Bug Report
Cannot see/edit user pages when browsing to them. A reload redirects to active user's profile page.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.3.1

## 🐜 Describe the bug

When I browse to user pages (including the actively logged in user's user page), the page is not displayed. If I reload the page, my (active user) profile page is loaded.

## 👉 Steps To Reproduce

1. Go to Users / Users & Groups / Public
1. Double click any user (eg. Alba Monday - but any user, even active user's user page behaves the same)
1. Reload the page

## 😯 Current behavior

* Before reload: User page is not loaded
* After reload: UI redirects to the active user's profile page

## 🤔 Expected behavior

Selected user's user page should appear.
On reload the same should happen: previously selected user's user page should appear.

## 🖼 Screenshots

Instead of a user's user page (Alba Monday) I see this:

![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/f3cd2a43-9c94-4097-9cd6-6786ad5ad9a9)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check [this pr](https://github.com/SenseNet/sn-client/pull/165) for the fix
