### ISSUE TITLE
[BUG] Profile link in User menu opens the User or Group opened for the last time instead of the profile of the active user

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#181]
# 🐜 Bug Report
Profile link in User menu opens the User or Group opened for the last time instead of the profile of the active user

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.3.1, bug found in [this pr](https://github.com/SenseNet/sn-client/pull/165) 

## 🐜 Describe the bug

If the (admin) user wants to open their personal profile from the User menu by clicking the Profile menu item, another User or Group content will open instead - the one that the user opened previously.

## 👉 Steps To Reproduce

1. Log in as an admin user, e.g. Business Cat.
1. Open a user or group content item from under the Users or Groups menu items. Open Alba Monday, for example.
2. Click Profile from the Users menu (will only work if you go to the Documents menu first).

## 😯 Current behavior

Wrong user profile opens (Alba Monday)

## 🤔 Expected behavior

My user profile should open instead (Business Cat)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check [this pr](https://github.com/SenseNet/sn-client/pull/165) for the fix
