### ISSUE TITLE
[controls-react] Missing fieldcontrols

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#185]
# 🙋 Feature Request

Some fieldcontrols are now unhandled but they're now needed on the admin-ui. Check the old fieldcontrols and templates, implement the ones that are necessary and handle the ones that can be skipped on the new ui. Remove all the the fieldcontrols tests because the storybook stories for the controls are enough to check if they're rendered without errors or not.

### Custom fieldcontrols
- [x] AllowedChildTypes (control for choosing type of the content items that can be created on the current level) - must
- [x] UrlList (control for adding or removing url-s for sites) - must (will be a simple LongText now)
- [x] ColorPicker (control for choosing a color value picking it on a palette) - nice to have
~~- [ ] HyperLink (control for setting a link with url, title and _target) - nice to have~~

### Fallback
- [x] ApprovingModeChoice > DropDown (ControlHint)
- [x] Currency > Number
- [x] QueryBuilder > LongText (it is a very complex control in the old version, another issue should be made and a lot of discussion before, but now it is enough to fallback to LongText)
- [x] Version > disabled ShortText (NullFieldSetting)
- [x] VersioningMode > DropDown (ControlHint)
- [x] VersioningModeChoice > RadioButtonGroup (ControlHint)
- [x] WholeNumber > Number (ControlHint)

### Should be skipped/removed/return null
*(They are not used anywhere on the new ui now)*
- [x] ButtonList
- [x] SiteRelativeUrl > ShortText
- [x] UploadBinary > Binary
- [x] ReferenceDropDown
- [x] PageTemplateSelector

**Comment by kultsar** [comment]
Let's talk:
- AllowedChildTypes does not work for me.
- [ ] I think that the color picker should not disappear on the first click. Now it does. It picks a color, so it works, but I just 1) cannot manually enter values for setting a color 2) cannot pull the pointer around the control(s) and see how the color changes
- Cannot find URL list control
