### ISSUE TITLE
[WOPI] Host page for documents in the browser

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#194]
@tusmester commented on [Wed Oct 24 2018](https://github.com/SenseNet/sensenet/issues/504)

To display documents in the browser, we need a **host page** that will host the Office Online iframe.

- https://wopi.readthedocs.io/en/latest/hostpage.html#host-page

> **Move this issue** to the appropriate repo when we start working on it.

---

@tusmester commented on [Mon Jan 21 2019](https://github.com/SenseNet/sensenet/issues/504#issuecomment-456007298)

I think we should provide an action only for the tokens and urls required by the html in the example above. The html should be assembled on the client and _not_ served by the server. 
@gallayl ?

---

@gallayl commented on [Mon Jan 21 2019](https://github.com/SenseNet/sensenet/issues/504#issuecomment-456042507)

I think we should try to generate the host page in the context of our SPA so the tokens and urls should be enough.

---

@herflis commented on [Tue May 14 2019](https://github.com/SenseNet/sensenet/issues/504#issuecomment-492291411)

- [x] add an example to the dms
- [x] discuss if part of the code could be outsourced to another package(s)
- [ ] discuss header and/or navigation back to the doclib

**Comment by kultsar** [comment]
I get page not found error messages for businesscat also.

**Comment by herflis** [comment]
@kultsar the office online url was not set in the settings file, but now it is, so pls check it again

**Comment by kultsar** [comment]
Works for admin, I think this can go to the release despite the blocker issues.
