### ISSUE TITLE
[BUG] Splash message greets previous user instead of logged in user

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#199]
# 🐜 Bug Report

Splash message sometimes greets visitor instead of logged in user.
Cannot always reproduce, but it seems that if delete all locally stored site data, then it is reproducible.

## 📦 Package / Application

sn-app

## 📃 Version

0.2.0

## 🐜 Describe the bug

Right after logging in as, eg. businesscat, the UI normally greets the user as "Greetings, Business Cat!", but sometimes I see "Greetings, Visitor!"

## 👉 Steps To Reproduce

1. Log in
2. Watch the greeting splash message

## 😯 Current behavior

_Sometimes_ it greets visitor instead of logged in user.

## 🤔 Expected behavior

It should always greet logged in user.

## 🖼 Screenshots

https://www.screencast.com/t/kITpZW3wvyGv
## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by kultsar** [comment]
Update: not necessarily visitor. Greetings splash message first greets previous user, then real logged in user

Examples:.
1. Never logged in with any user before
1. Log in with businesscat
1. Splash should greet businesscat, but sometimes may greet visitor, then switch to businesscat

or

1. Login with alba
1. Log in with businesscat
1. Splash should greet businesscat, but sometimes may greet alba, then switch to businesscat

**Comment by gallayl** [comment]
fixed in the referenced PR

**Comment by kultsar** [comment]
Might need to reopen this. Previously it was ok, now somehow behaves as before the fix.

**Comment by gallayl** [comment]
@kultsar  where did you test it? The referenced PR is **NOT** merged back to dev. it has additional changes and awaiting for approval.
