### ISSUE TITLE
[BUG] System tries to log in with empty repo URL

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#200]
# 🐜 Bug Report

When URL repo is left empty in the login box, the system should just warn user, and not try to log in.

## 📦 Package / Application

sn-app

## 📃 Version

0.2.0

## 🐜 Describe the bug

When URL repo is left empty in the login box, the system should just warn user, and not try to log in.

## 👉 Steps To Reproduce

1. Click Another repository button
1. Fill in Username and password fields
1. Leave repository URL empty
1. Click Login button

## 😯 Current behavior

System tries to log in and shows notification message about unsuccessful login to "".

## 🤔 Expected behavior

Should tell user to "Please fill out this field", and not try to log in.

## 🖼 Screenshots

Screencast: https://www.screencast.com/t/mgHfe7Bsdb

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by gallayl** [comment]
fixed in the referenced PR
