### ISSUE TITLE
[BUG] Assigning wrong value to theme results in white screen

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#202]
# 🐜 Bug Report

When the user assigns a wrong value to theme in personal settings, white screen follows, and the local storage must be deleted in order to access the app again.

## 📦 Package / Application

sn-app

## 📃 Version

0.2.0

## 🐜 Describe the bug

When the user assigns a wrong value to theme in personal settings, white screen follows, and the local storage must be deleted in order to access the app again.

## 👉 Steps To Reproduce

1. Change theme to "wrongvalue"
1. Save

## 😯 Current behavior

White page

## 🤔 Expected behavior

Perhaps system should default to a theme

## 🖼 Screenshots

https://www.screencast.com/t/XvsjZhrnrPn

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by gallayl** [comment]
fixed in the referenced PR
