### ISSUE TITLE
[BUG] Failed login to invalid url repo prevents login to valid url repo

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#203]
# 🐜 Bug Report

Failed login to bad url repo prevents login to good url repo
## 🐜 Describe the bug

A previous failed login to bad url repo prevents login to good url repo.

## 👉 Steps To Reproduce

1. Log in with valid url repo
1. Log out
1. Try to log in with invalid url repo
1. Try to log in with valid url repo

## 😯 Current behavior

Cannot login. Error message refers to bad url repo. Until user reloads the page, cannot log in to any valid url repo.

## 🤔 Expected behavior

Should be able to log in.

## 🖼 Screenshots

https://www.screencast.com/t/seUPJC02js

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by gallayl** [comment]
fixed in the referenced PR
