### ISSUE TITLE
[BUG] Switching to repo with expired session should only show login window

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#205]
# 🐜 Bug Report

Switching to repo with expired session should only show login window and nothing from previous UI. We should not let unauthorized users read data from the screen.

## 📦 Package / Application

sn-app
## 📃 Version
0.2.0

## 🐜 Describe the bug
Switching to repo with expired session should only show login window

## 👉 Steps To Reproduce

1. Log in to 2 different repos, eg. devservice and dmsservice
1. Switch to dmsservice
1. Expire devservice
1. Switch to devservice
1. User should only see login window, and nothing else from previous session (no dashboard, nothing).

## 😯 Current behavior

unauthorized user sees previous ui

## 🤔 Expected behavior

should only see login window

## 🖼 Screenshots

https://www.screencast.com/t/zBYcPGMiSHDD
## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by gallayl** [comment]
The browser won't fire any event if you delete a cookie so the app cannot handle this scenario. The next request will be unauthorized so I think this is not a security issue.

**Comment by kultsar** [comment]
I can accept, but first lets talk, I don't fully understand the situation.

Would it be possible that after user initiates action to switch to a target repository we check if that session expired or not, and if the result is that it expired, we do not show the UI for that repo, just a login screen? I would not like to show anything from the UI (dahsboard, etc) to unauthorized users, if possible. If not, then ok.

**Comment by gallayl** [comment]
1. the next request will kick out the user and she will be forced to refresh the page and log in again
1. if we will have an ordinary dashboard component that fetches info, it will fire that request that will do the trick
1. the placeholder dashboard with Master Roshi doesn't contains any sensitive info

So I don't agree that we should hard code checks on repository switching at the moment.
