### ISSUE TITLE
[FEATURE] Switching between repos should update login window contents

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#206]
# 🙋 Feature Request

Switching between repos should update login window contents
## 📦 Package / Application

sn-app
## 📃 Version
0.2.0

## 🤔 Expected Behavior
Switching between repos should update login window contents

## 😯 Current Behavior
It just shows last used repo data. Which is fine if I just open the app, but when I switch repo, I want to use that repo, and I want to log in to that repo if I'm logged out of it.

https://www.screencast.com/t/EyGBwAoufnj

## 💁 Possible Solution
Switching between repos should update login window contents

**Comment by gallayl** [comment]
fixed in the referenced PR

**Comment by kultsar** [comment]
Sorry, I was not clear enough. Can we update the user as well?
