### ISSUE TITLE
[BUG] Login button pushed to the right by error message

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#211]
# 🐜 Bug Report

Login button is pushed to the right from the center by the "Wrong user name or password" error message.

## 📦 Package / Application

sn-dms-demo
## 📃 Version
1.4.0

## 🐜 Describe the bug
After unsuccessful login due to bad username or password the Wrong username or password message appears, but this pushes the Login button from the center to the right.

## 👉 Steps To Reproduce

1. Fill in both username and password fields. One of them should be wrong
1. Click Login
1. Wrong username or password error appears

## 😯 Current behavior

Login button is pushed to the right.

## 🤔 Expected behavior

Login button is should stay put, in the center.

## 🖼 Screenshots

https://www.screencast.com/t/PWGjIoJemafe
## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar you can check the fix [here](https://github.com/SenseNet/sn-client/pull/218/)
