### ISSUE TITLE
[BUG] Configure Recaptcha for frontend release DMS environment

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#213]
# 🐜 Bug Report
Recaptcha not working in frontend release DMS environment

## 📦 Package / Application
sn-dms-demo

## 📃 Version
some earlier version

## 🐜 Describe the bug
Users cannot register as recaptcha is not working on the registration tab.

## 👉 Steps To Reproduce

1. open login screen for visitor users
1. click over to register tab
1. recaptcha error appears instead of recaptcha function

## 😯 Current behavior

recaptcha should work

## 🤔 Expected behavior
it does not

## 🖼 Screenshots
![image](https://user-images.githubusercontent.com/39081660/58108410-1832ee00-7bec-11e9-8078-ad70c304d0a4.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by herflis** [comment]
@kultsar how did you check this? I cannot switch to the register tab on dms.demo.sensenet.com

**Comment by kultsar** [comment]
Ummm... I also cannot switch. Will have to wait till release environment is fixed, and then will recheck this issue.
