### ISSUE TITLE
[UX] Admin UI Use cases user validation - 1st block

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#220]
* Login
* Logout
* Switching repositories
* Personal settings

https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/WopiFrame.aspx?sourcedoc={b5e9aea8-68e5-4ffc-9512-f4d49c709574}&action=edit&wd=target%28Admin%20ui.one%7C253c21f4-a1b4-44ef-8414-8000f6ad35a5%2FLogin%7Cc55b8e39-b3b2-481a-96bc-8ac00f3e9754%2F%29

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin UI 1.0](https://trello.com/c/db78sCs9/3-admin-ui-10)
