### ISSUE TITLE
[BUG] Successful registration does not redirect to login screen

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#222]
# 🐜 Bug Report

Successful registration does not redirect to login screen

## 📦 Package / Application

sn-dms-demo

## 📃 Version

1.4.0
## 🐜 Describe the bug

Successful registration does not redirect to login screen

## 👉 Steps To Reproduce

1. Open app as Visitor
1. Click Register tab
1. Fill in with correct values and click Register

## 😯 Current behavior

User is created, but UI does not redirect to Login screen.

## 🤔 Expected behavior

Should redirect.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check the fix [here](https://github.com/SenseNet/sn-client/pull/218)

**Comment by kultsar** [comment]
Can only test in an environment with reCAPTCHA configured

**Comment by herflis** [comment]
@kultsar You can check it now on the [dev site](https://sn-dms-demo-dev.netlify.com/#/registration)
