### ISSUE TITLE
[BUG] Empty password error message under wrong field on registration page

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#223]
# 🐜 Bug Report

When the user tries to register but does not fill in the Confirm password field, the related error message is displayed under the Password field. It should display under the Confirm password field.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.4.0

## 🐜 Describe the bug
When the user tries to register but does not fill in the Confirm password field, the related error message is displayed under the Password field. It should display under the Confirm password field.

## 👉 Steps To Reproduce

1. Go to Register page
1. Enter something into the Password field
1. Leave Confirm password field empty
1. Leave the field (focus should not be in the field) 

## 😯 Current behavior

"Password needs to contain at least 3 characters!" error message appears under the Password field

## 🤔 Expected behavior

"Password needs to contain at least 3 characters!" error message should appear under Confirm password.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar check the fix [here](https://github.com/SenseNet/sn-client/pull/218)
