### ISSUE TITLE
[BUG] Search by owner does not work

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#225]
# 🐜 Bug Report
Search by owner does not work

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.4.0

## 🐜 Describe the bug

Search by owner does not produce a hitlist, but it should.

## 👉 Steps To Reproduce

1. Logint with businesscat
1. Go to your doclib
1. Open advanced search dialogue
1. Enter "businesscat@sensenet.com" into Owner field, and click Search

## 😯 Current behavior
Does not return hitlist, it's empty.

## 🤔 Expected behavior

Should return hitlist, since there are contents with bcat owner.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar You can check the fix [here](https://github.com/SenseNet/sn-client/pull/251)
