### ISSUE TITLE
[BUG] Cannot search for Modification date with Advanced search

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#227]
# 🐜 Bug Report
Cannot search for Modification date with Advanced search

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.4.0

## 🐜 Describe the bug
Cannot search for Modification date with Advanced search.

## 👉 Steps To Reproduce

1. Go to a doclib
1. Open advanced search dialogue.
1. Set a date in Date modified (eg Yesterday)

## 😯 Current behavior

1. Hitlist is empty.

## 🤔 Expected behavior

1. Hitlist should list contents modified since the date set.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by herflis** [comment]
@kultsar You can check the fix [here](https://github.com/SenseNet/sn-client/pull/251)
