### ISSUE TITLE
[testing] e2e tests for Login

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#239]
[usecases](https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/WopiFrame.aspx?sourcedoc={5b78342d-a691-4d43-9b61-b2f58158f9b6}&action=edit&wd=target%28admin-ui.one%7C529be6a4-bd90-487a-839c-57244e6eed0f%2FLogin%7C285d7d0c-f45d-4d31-81ce-f607213e8361%2F%29)

**Comment by tusmester** [comment]
Closed as obsolete.
