### ISSUE TITLE
[dms-demo] User profile browse page

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#24]
@kultsar commented on [Tue Oct 09 2018](https://github.com/SenseNet/sn-dms-demo/issues/387)

- [x] basic fields
- [x] list of groups user assigned to
	- [x]  group name
	- [x] workspace the group belongs to
	- [x] delete from group (only seen for group admins)
- [x] add to group (see user, edit group)
- [x] remove from group (see user, edit group)

**Comment by kultsar** [comment]
Adding group to user:
* [ ] Cannot unselect a group
* [ ] Selecting a group selects it in the background (in the user profile group list) as well
* [ ] If the group to add is located in a deep hierarchy, group name is not seen due to the long path. Should show name to user somehow, perhaps by a balloon tooltip 

Group list user belongs to:
* [ ] Ordering only works for group name (display name) column, but not for the other two columns
* [ ] Groups that the user belongs to through inheritance could be listed with a non-removable checkmark (if not a big effort)

**Comment by herflis** [comment]
[https://deploy-preview-107--sn-dms-demo-dev.netlify.com](https://deploy-preview-107--sn-dms-demo-dev.netlify.com)
