### ISSUE TITLE
[testing] e2e tests for Registration

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#240]
Create e2e tests with cypress for Registration by [these use cases](https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/WopiFrame.aspx?sourcedoc={b5e9aea8-68e5-4ffc-9512-f4d49c709574}&action=edit&wd=target%28DMS%20demo.one%7C8cf482a1-b344-43ab-a6be-aeb1ef704074%2FRegistration%7Ca483f70c-92d5-4950-881d-b0fc36186bd9%2F%29)

**Comment by tusmester** [comment]
Closed as obsolete.
