### ISSUE TITLE
[testing] e2e tests for usermenu

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#241]
Create e2e tests with cypress for Usermenu by [these use cases](https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/WopiFrame.aspx?sourcedoc={b5e9aea8-68e5-4ffc-9512-f4d49c709574}&action=edit&wd=target%28DMS%20demo.one%7C8cf482a1-b344-43ab-a6be-aeb1ef704074%2FUsermenu%7C672bbb57-4fff-4473-906a-3ed4d4f84996%2F%29)

**Comment by tusmester** [comment]
Closed as obsolete.
