### ISSUE TITLE
[ENHANCEMENT] Clean up after cra in dms

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-client#254]
# 🙋 Feature Request

We should clean up after Create React App in dms-demo.

## ⚙ Tasks

- [x] Remove config, scripts folders (we don't use them)
- [x] Review dependecies (cra puts everything to dependecies. Remove those that we don't use and move those that are dev dependecies to devDependecies)

**Comment by RanadeepPolavarapu** [comment]
I'll take this.

**Comment by B3zo0** [comment]
Done in #408
