### ISSUE TITLE
[FEATURE] New folder location in copy/move dialogue

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#258]
# 🙋 Feature Request

When users are about to create a new folder from copy/move dialogue, the location of the new folder is not clear, causing confusion. We need to make it clear.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.4.1

## 🤔 Expected Behavior

Users should be informed about the location of the new folder to be created.

## 😯 Current Behavior

Confusing. User does not know if new folder is created in the current folder or the selected one.

## 💁 Possible Solution

Regardless where the new folder is about to be created (we can change this behavior later, regardless of the current issue), we should display the folder name (in which in the new folder will be created) in the dialogue title. Eg. "Create new folder in [existing_folder]"

## 💻 Examples
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/ac6929f5-9839-4d7c-8178-978898d405bb)

**Comment by CsabaPeter** [comment]
The first best practice scenario is with Google Drive when you want to create a new folder while moving another file it tells you in a popup window where it will create the new folder. After you accept your folder will be created and on the same popup window now you can see the created folder and move the file there.

**Comment by CsabaPeter** [comment]
![Dropbox_1](https://user-images.githubusercontent.com/38352683/58870357-5b975d00-86c0-11e9-83b5-9267179c6803.png)
![Dropbox_2](https://user-images.githubusercontent.com/38352683/58870358-5b975d00-86c0-11e9-9fd1-6bca31796341.png)
![Dropbox_3](https://user-images.githubusercontent.com/38352683/58870361-5c2ff380-86c0-11e9-96f7-25a93f8ef1b9.png)

Second best practice scenario: Dropbox. When you want to create new folder it will show you all the existing folders in a popup window where you can click on a folder and then it will be created inside that folder. You can do this as many times you want. In a breadcrumb it will show you how deep you are in the folder structure and clicking on the folder names it will jump back into that folder. It gives you the freedom to create as many folders you want and move the file where you like in the structure.
