### ISSUE TITLE
[react-component-docs] Integrate search component to Storybook

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#26]
@kultsar commented on [Mon Nov 12 2018](https://github.com/SenseNet/sn-react-component-docs/issues/3)

Similar to https://github.com/SenseNet/sn-dms-demo/issues/409

**Comment by kultsar** [comment]
Cannot find where to test.

**Comment by gallayl** [comment]
I've created a Netlify site from the monorepo's develop branch, you can check it there: https://sn-react-component-docs-dev.netlify.com/

**Comment by kultsar** [comment]
Reference field:
* when typing, loses focus, have to click into the field for each letter I type
* dropdown always remains the same, does not matter if field is empty or user types in anything
