### ISSUE TITLE
[BUG] Changing eventLogSize to a string (with quotes) should not be allowed

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#261]
# 🐜 Bug Report

Changing eventLogSize in personal settings to a string (with quotes) is allowed by the system. It should not be allowed.

## 📦 Package / Application
sn-app

## 📃 Version
0.3.0

## 🐜 Describe the bug

When user changes to wrong value, personal settings can be saved.

## 👉 Steps To Reproduce

1. Go to personal settings
1. Chane eventLogSize to a string (with quotes)
1. Click Save

## 😯 Current behavior

Personal settings are saved.

## 🤔 Expected behavior

It should not be saved, and an error message should pop up

## 🖼 Screenshots
https://www.screencast.com/t/qu7QKMPgB

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by gallayl** [comment]
Why shouldn't we allow that? It's the same scenario as [setting the theme to the wrong value](https://github.com/SenseNet/sn-client/issues/202). We can **allow** or **disallow** all type checks (that are warnings / underlined with green) at the moment.
