### ISSUE TITLE
[BUG] Changing unquoted string to quoted should not be allowed in personal settings

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#262]
# 🐜 Bug Report
Changing unquoted string to quoted should not be allowed in personal settings

## 📦 Package / Application
sn-app

## 📃 Version
0.3.0

## 🐜 Describe the bug
User is allowed to change unquoted string to quoted string.

## 👉 Steps To Reproduce

1. Open personal settings
1. User changes enabled under commandPalette from true to "false" - with quotes
1. User clicks Save button

## 😯 Current behavior
Save is performed without any error

## 🤔 Expected behavior
Save should not be performed, user should receive an error message

## 🖼 Screenshots

https://www.screencast.com/t/sIxLrF6Djg

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by gallayl** [comment]
Why shouldn't we allow that? It's the same scenario as [setting the theme to the wrong value](https://github.com/SenseNet/sn-client/issues/202). We can **allow** or **disallow** all type checks (that are warnings / underlined with green) at the moment.
