### ISSUE TITLE
[BUG] Cannot open folder on mobile

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#268]
# 🐜 Bug Report

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by tusmester** [comment]
Closed as obsolete.
