### ISSUE TITLE
[BUG] Placeholder menu item names

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#273]
# 🐜 Bug Report

Some menu items have a placeholder name. And yesterday they did not. Except for the checkout related one, it was like this yesterday also.

## 📦 Package / Application
sn-dms-demo

## 📃 Version
1.4.1

## 👉 Steps To Reproduce

* Click New button in Doclib grid
and
* Select Check out in 3dots menu item in grid next to an item

## 😯 Current behavior

Many new menu items and a 3dot menu item have a placeholder name (after checking out the item)

## 🤔 Expected behavior

They should not

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/59025724-16586400-8855-11e9-9f1c-f6da8f6be0ab.png)

![image](https://user-images.githubusercontent.com/39081660/59025900-80710900-8855-11e9-82f3-8828a9630234.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by herflis** [comment]
@kultsar can you pls check it again after clearing the cache in your browser? I cannot reproduce this issue

**Comment by kultsar** [comment]
- [ ] 3dot menu item still has a placeholder name

As for the new items, clearing the cache solved it.
