### ISSUE TITLE
[BUG] Viewer does not load (update) document choosing from the search results dropdown

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#274]
# 🐜 Bug Report

Viewer does not load (update) document choosing from the search results dropdown on the admin-ui

## 👉 Steps To Reproduce

1. Login as businesscat
2. Navigate to /workspaces/project/budapestprojectworkspace/document_library 
3. Open a document with the viewer
2. Search for FitnessTracker.ods and click the name of the file in the dropdown

## 😯 Current behavior

Viewer does not load the chosen document

## 🤔 Expected behavior

Viewer should load the chosen document

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by B3zo0** [comment]
I moved this bug to review because I couldn't reproduce it.
