### ISSUE TITLE
[FEATURE] Upload progress on admin-ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#276]
# 🙋 Feature Request

- [x] when the user hits the upload button or drops content to the list or the breadcrumb/tree/etc a dialog will open with the files that should be uploaded or empty if after hitting the upload button
- [x] the user can add files to the dialog with clicking on it or with drag and drop
- [x] the following data should be displayed per file:
   - [x] filename/if the file is uploaded as a part of a folder structure their path should be displayed
   - [x] size
   - [x] delete button till the upload is not started
- [x] upload button, drag and drop, delete and dialog close are disabled during the upload progress
- [x] dirty for check while the upload is in progress
- [x] dialog remains open after upload

**Comment by CsabaPeter** [comment]
Best practices:
Contentful:

![Contenful_1](https://user-images.githubusercontent.com/38352683/63432865-4f4eb080-c422-11e9-9c25-9731e8c53942.png)
![Contenful_2](https://user-images.githubusercontent.com/38352683/63432866-4f4eb080-c422-11e9-95e6-f06da6500483.png)
![Contenful_3](https://user-images.githubusercontent.com/38352683/63432867-4f4eb080-c422-11e9-82cc-2ada7fcb4039.png)
![Contenful_4](https://user-images.githubusercontent.com/38352683/63432868-4f4eb080-c422-11e9-9a26-7f504ff0965a.png)

DotCMS:

![Dot_1](https://user-images.githubusercontent.com/38352683/63432884-5aa1dc00-c422-11e9-9de2-47dd9a44ac19.png)
![Dot_2](https://user-images.githubusercontent.com/38352683/63432885-5aa1dc00-c422-11e9-97c2-1060db49ae92.png)
![Dot_3](https://user-images.githubusercontent.com/38352683/63432886-5b3a7280-c422-11e9-9530-cf72c2143848.png)
![Dot_4](https://user-images.githubusercontent.com/38352683/63432887-5b3a7280-c422-11e9-8d5d-56779f1c74d3.png)

**Comment by herflis** [comment]
https://xd.adobe.com/view/87faeebf-de35-4f8e-62a4-62955b96a222-f1cb/

**Comment by B3zo0** [comment]
Maybe we should show the path to the content where the documents will be uploaded. What do you think?
