### ISSUE TITLE
Admin-ui dashboard ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#281]
Things that should be displayed on the admin-ui 1.0 dashboard (M means it is also should be displayed on mobile):

- [ ] Welcome widget (avatar, fullname, welcome text) (M)
- [ ] Updates widget (from version info, 'packages to update' list and link to version info, if the list is empty then display the sun) (M)
- [ ] Stats: number of users, number of content items, content items updated in the last x days (since yesterday)
- [ ] Links to docs, tutorials, etc
- [ ] Contact us (link) (M)
- [ ] Query with results (M)
	○ Docs owned by me
	○ Docs shared with me

**All the widgets should have a ui with empty results/no users/no content.**
***************
- [ ] My tasks (M)
- [ ] Waiting for approval (M)
- [ ] Markdown widget (e.g. static repo info or welcome widget)
- [ ] Embedded webpage (last 5 posts from the blog)

**Comment by CsabaPeter** [comment]
https://xd.adobe.com/view/c271071e-9084-40fe-4037-e753be5312d9-b440/

![Dash](https://user-images.githubusercontent.com/38352683/59504038-3f56a580-8ea2-11e9-9dd1-5843cad5149e.png)

**Comment by gallayl** [comment]
@CsabaPeter can we split the "Docs owned by me" and "Docs shared with me" sections into two cards?

**Comment by CsabaPeter** [comment]
@gallayl Yes, it's updated on the attached link

**Comment by CsabaPeter** [comment]
Attached the desktop dashboard. You can check it in the updated link as well.
![Dashboard_Desktop](https://user-images.githubusercontent.com/38352683/59678851-bd31ee00-91cd-11e9-9e16-003b3302183c.png)
![Dashboard_Desktop_Empty](https://user-images.githubusercontent.com/38352683/59678852-bd31ee00-91cd-11e9-85a0-824f5d903d91.png)
