### ISSUE TITLE
[BUG] Edit properties dialogue disappers on first click

### ISSUE THREAD

**Issue by molnarm84** [SenseNet/sn-client#285]
# 🐜 Bug Report

Edit properties dialogue disappears on first click

## 📦 Package / Application
sn-app

## 📃 Version
0.3.0

## 👉 Steps To Reproduce

1. opening grid
2. click on 3 dots menu on any content item
3. click edit properties
4. nothing happenes

## 😯 Current behavior
1. opening grid
2. click on 3 dots menu on any content item
3. click edit properties
4. nothing happenes

## 🤔 Expected behavior
1. opening grid
2. click on 3 dots menu on any content item
3. click edit properties
4. open the window to edit

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by B3zo0** [comment]
I can not reproduce this. Is this still an issue @molnarm84 ?
