### ISSUE TITLE
[document-viewer] Call GetExistingPreviewImages on PageCount -4

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#320]
PageCount -4 (Postponed) should be handled as a case when the preview generation should be started manually with GetExistingPreviewImages action.

**Comment by tusmester** [comment]
`GetExistingPreviewImages` will return 0 in this case without starting preview generation. I'd suggest using `RegeneratePreviews` in case the status is -4 (postponed). It will set the status to -1 (in progress) and start generating preview images.
