### ISSUE TITLE
[list-controls-react] Upload popup modifications

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#33]
@kultsar commented on [Wed Aug 08 2018](https://github.com/SenseNet/sn-list-controls-react/issues/16)

Talked to UX about upload list:
- [ ] Ordering: the file that had been uploaded most recently should be in the top of the list and the whole list should go from latest to oldest.
- [ ] User should be able to remove files one by one (possibly with an (X) icon next to each file) and a clear all button on the top of the list.
- [ ] Failed uploads: The failed files should be on top of the list where the user can see which files were not uploaded.

**Comment by tusmester** [comment]
Closed as obsolete.
