### ISSUE TITLE
[admin-ui] admin-ui login page revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#330]
There're some missing pieces on the admin-ui login page that should be placed somewhere even if the background feature is not ready yet:

### Should be added
- some welcome text
- sign up link
- reset/forgotten password link
- contact support link
- link to some of the related docs as **help**
- sso
- github login
- google login

### Examples

[https://be.contentful.com/login](https://be.contentful.com/login)
[https://kentico.auth0.com/login](https://kentico.auth0.com/login?state=g6Fo2SBtaUw5ZklmeFF0cnQ4MUNLYVh5UWNYV1U2QVlQeTg4aaN0aWTZIER2WUFheHdrVHFhcnROVkpfcU9JV25Jdnk3clEyNjlLo2NpZNkgUlJ0OG1oUkl1RUZFbGE3cVZhZHVuTFM4XzgtZmRhcmk&client=RRt8mhRIuEFEla7qVadunLS8_8-fdari&protocol=oauth2&response_type=token%20id_token&redirect_uri=https%3A%2F%2Fapp.kenticocloud.com%2Fcallback&audience=https%3A%2F%2Fapp.kenticocloud.com%2F&nonce=6D6U5pmAUeBzdCChUYEw5l4-1FRhK30F&scope=openid%20profile%20email&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMS4xIn0%3D)
[https://manager.agilitycms.com/login](https://manager.agilitycms.com/login)

**Comment by CsabaPeter** [comment]
![Login](https://user-images.githubusercontent.com/38352683/62456323-75185c00-b778-11e9-89ce-7adfa1662df6.png)
