### ISSUE TITLE
[document-viewer] Closing the docviewer

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#336]
The user should be able to close the viewer somehow.
- [x] The user should be able to close the viewer with the esc key
- [x] There should be a close button or icon somewhere on the ui (@CsabaPeter pls help us where to put the button/icon) 
- [ ] There should be a close icon at the top right corner
- [ ] If the user clicks outside the viewer ti should be closed too (?)

**Comment by CsabaPeter** [comment]
The close button should be on the top right corner with bold text to stand out and should be easily recognized.
Sample:
![Screen Shot 2019-08-05 at 11.05.57.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/b83d626a-46d7-4e74-acaf-e7b1fadd2b47)
