### ISSUE TITLE
[admin-ui] Actions should work consistently

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#354]
## 😯 Current behavior

1. devdog (/Root/IMS/Public/devdog) is a demo user in the dev.demo.sensenet.com in the who is a member of the public Developers group (/Root/IMS/Public/Developers)
2. Save permission is allowed (no Delete !!!) for the public Developers group on 20 assorted content types (e.g. Folder, File)
3. If devdog opens the content types 'page' on the admin-ui it shows the correct list of ctd's but if he opens the actionmenu, it lists more actions than it should, for example the Delete action.
4. If the user choose delete, and let the system send a delete request for the chosen ctd it is aparently done, the user gets a notification that it was successfully deleted, even tough there's an error message in the response .

## 🤔 Expected behavior

~- [ ] The best will be if the actions that cannot be executed with an content (e.g. are Forbidden) will not be listed in the actionlist~
- [x] If it is not possible to load items of the actionlist dynamically then please fix the notification after delete request.
- [x] Delete action is only an example, other actions may be affected

**Comment by gallayl** [comment]
Verified on Copy/Move, implemented on Delete actions, they should be OK.
