### ISSUE TITLE
[admin-ui] Displaying drawer menuitems by permissions

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#355]
The drawer items should be displayed if the current user has permissions to see them 

- [x] Search can be displayed for everyone
- [ ] 'Content' should be listed if the user has Open permission on the given branch/root
- [ ] 'Users and groups' should be listed if the user has AddNew permission on the /Root/IMS/Public domain
- [ ] 'Content types' should be displayed if the user has AddNew permission on /Root/System/ContentTypes
- [ ] 'Localization' should be displayed if the user has AddNew permissions on /Root/Localization
- [ ] 'Setup' should be displayed if the user has Open permission on /Root/System/Settings
- [ ] 'VersionInfo' should be displayed if the user has RunApplication permission on the VersionInfo action

**Comment by gallayl** [comment]
I've encountered a problem with this approach - the user needs a ``SeePermissions`` permission (and ``RunApplication`` on the related action).
