### ISSUE TITLE
[admin-ui] Contextmenu should load menuitems per content

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#379]
- [x] contextmenu should load the Actions that are available on the content 
- [x] actions should be loaded with ```/Actions``` on click or with expanding the actions when the content is loaded
- [ ] custom menu item with custom logic can be added to the contextmenu

-----------------

/Actions?scenario=ContextMenu

Browse
CopyTo
MoveTo
Edit
// Set permissions
Versions
CheckIn
CheckOut
Publish
Approve
Reject
UndoCheckOut
ForceUndoCheckout
Delete
WopiOpenEdit/WopiOpenView
Preview
// Set notification
// Workflows

**Comment by B3zo0** [comment]
> custom menu item with custom logic can be added to the contextmenu
This is currently not supported. Maybe in the future. Right now you can use the command palette to trigger custom actions on content.
