### ISSUE TITLE
[BUG] Open an old repository without /Root/Content

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#380]
In the new version is a must to have the Content workspace under the /Root and one of the menuitems is also connected so the admin ui now broken for those who login to an old repository.
Check if the /Root/Content is not available and create it than or if it is not possible load /Root/Sites instead of /Root/Content.

**Comment by gallayl** [comment]
I've failed to reproduce the bug in the latest DEV branch. I think the current behavior should be the expected one:
 - If the /Root/Content is available and can be opened, display it
 - If it doesn't, we threat it as the user doesn't have permission to it.

I think as it's a dynamic value (any content can be placed on the drawer) we shouldn't hard code a fallback to /Root/Sites - If anyone uses a legacy / *non-standard* site, she can adjust the drawer in the settings
