### ISSUE TITLE
Authentication: connect to IdentityServer from the browser

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#394]
Collect all use cases and artifacts to create for authenticating from the browser. This is a spike.

- http://docs.identityserver.io/en/latest/endpoints/discovery.html
- https://github.com/IdentityModel/oidc-client-js
- https://github.com/ThunderDev1/reactjs-ts-identityserver

**Comment by B3zo0** [comment]
Created #492 for follow up task.
