### ISSUE TITLE
Add missing dependencies to packages

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-client#396]
There are some missing dependecies in some of our packages. We need to add them to package.json and the tsconfig.json if it is our package.

## Missing dependencies

🌀 needs to be added to tsconfig.json
📦 needs to be added to package.json

- [x] @sensenet/authentication-jwt
  - [x] tslib 📦
- [x] @sensenet/authentication-google
  - [x] tslib 📦
- [x] @sensenet/client-core
  - [x] tslib 📦
- [x] @sensenet/client-utils
  - [x] tslib 📦
- [x] @sensenet/control-mapper
  - [x] tslib 📦
- [x] @sensenet/controls-react
  - [x] tslib 📦
- [x] @sensenet/default-content-types
  - [x] tslib 📦
- [x] @sensenet/document-viewer-react
  - [x] @furystack/inject 📦
  - [x] tslib 📦
- [x] @sensenet/hooks-react
  - [x] @furystack/inject 📦
  - [x] @furystack/logging 📦
  - [x] semaphore-async-await 📦
  - [x] tslib 📦
- [x] @sensenet/icons-react
  - [x] tslib 📦
- [x] @sensenet/list-controls-react
  - [x] tslib 📦
- [x] @sensenet/pickers-react
  - [x] @sensenet/client-utils 🌀📦
  - [x] tslib 📦
- [x] @sensenet/query
  - [x] tslib 📦
- [x] @sensenet/redux-promise-middleware
  - [x] tslib 📦
- [x] @sensenet/redux
  - [x] tslib 📦
- [x] @sensenet/repository-events
  - [x] @sensenet/default-content-types 🌀📦
  - [x] tslib 📦
- [x] @sensenet/search-react
  - [x] @sensenet/client-utils 🌀📦
  - [x] tslib 📦

## Other tasks
- [x] remove tslib from the root package.json

**Comment by sajarindider** [comment]
Hey @B3zo0, I'd like to be assigned to this issue if possible. As for adding the dependencies, where they be added in the package.json file of the individual packages, devDependencies or dependencies? My gut tells me they should be added under devDependencies but I just want to be completely sure.

**Comment by B3zo0** [comment]
Hi @sajarindider.
These are all dependencies.
Don't hesitate to reach me if you have questions.

**Comment by B3zo0** [comment]
Fixed in #410
