### ISSUE TITLE
Move @furystack/inject and logging to client-utils

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-client#397]
Because @gallayl is leaving our team we agreed that the packages from `@furystack` should be moved to client-utils.

Tasks:

- [ ] use kebab-case for file names
- [ ] move https://github.com/furystack/furystack/tree/master/packages/logging to client-utils
- [ ] move https://github.com/furystack/furystack/tree/master/packages/inject to client-utils
- [ ] update packages that uses `@furystack` dependency to use it from client-utils

**Comment by Rupeshiya** [comment]
@B3zo0  How to reproduce this issue ?
I would love to work on this .

**Comment by B3zo0** [comment]
Hi @Rupeshiya sorry for the delayed answer.
This is not something that can be reproduced. Please read the issue again.

**Comment by Rupeshiya** [comment]
oh my bad @B3zo0 , I haven't read those task points. I will try to fix this.
Can I send WIP PR and get your view?

**Comment by B3zo0** [comment]
Sure, go ahead.

**Comment by Attila816** [comment]
hello I am working on it

**Comment by Attila816** [comment]
PR is created: https://github.com/SenseNet/sn-client/pull/437

**Comment by B3zo0** [comment]
Fixed in #437
