### ISSUE TITLE
🙋 [controls-react] Oembed integration into the Richtext editor

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#400]
It will be awesome if the user would be able to embed videos, images, etc with pasting url-s into the richtext editor.

_[oEmbed](https://oembed.com/) is a format for allowing an embedded representation of a URL on third party sites. The simple API allows a website to display embedded content (such as photos or videos) when a user posts a link to that resource, without having to parse the resource directly._

So the actual task is to integrate oEmbed into [quill](https://quilljs.com/) editor (that is the base of our richtext control) as a [custom module](https://quilljs.com/guides/building-a-custom-module/) for inserting links as embedded content

**Comment by geisterfurz007** [comment]
I would like to have a go on this!

Just to make sure: The idea is to develop a module for quill that would do the following when the user (for example because that was the example on the oembed page) pastes http://www.flickr.com/services/oembed/?format=json&url=http%3A//www.flickr.com/photos/bees/2341623661/

 1. Makes that request
 2. Parses the oEmbed response (as outlined in the oEmbed link)
 3. Adds the image to the body of the editor immediately

Is that what would need to happen? Or did I misunderstand what kind of URL would have to be added or where the image would go afterwards?

**Comment by herflis** [comment]
Hey @geisterfurz007 ,
yes, the tasks are exactly those you've mentioned 😊

**Comment by geisterfurz007** [comment]
Perfect! One last question: Where should the module go?

Would I move RichTextEditor.tsx to its own folder RichTextEditor and put the module in there as well? In that case, would I need to change the path to the RTE anywhere?

**Comment by herflis** [comment]
Yeah, please create a folder for the RichTextEditor stuff and move the .tsx there as well. As I see the imports and other references, you do not have to change the path anywhere. Maybe it has to be changed in the docs, but do not worry about it, the docs need to be updated by us anyway. 🙂

**Comment by geisterfurz007** [comment]
Hey there!

I managed to put a very, very rough example together with what I currently got over [here](https://github.com/geisterfurz007/Quill-OEmbed-Example).

To try it out, clone it, run `yarn` and then go to `node_modules/@sensenet/controls-react/dist/fieldcontrols/RichTextEditor.js` and add `oembed: true` to the modules. Run `yarn start` and you should be able to paste some oembed links into the editor.

A few example ones to try:

https://api.gfycat.com/v1/oembed?url=http%3A%2F%2Fwww.gfycat.com%2Ffearlesscookedamericangoldfinch (oembed type video)
https://codesandbox.io/oembed?url=https://codesandbox.io/s/new&format=json (oembed type rich)
https://api.geograph.org.uk/api/oembed?url=http://www.geograph.org.uk/photo/2928776&format=json (oembed type photo)

Unfortunately while I was testing them, it seems that a big amount of oembed providers do not have the proper CORS headers which leads to oembed link to for example youtube being useless but I don't think that's anything that can be solved on this end.

A few things I am still working on:

 - [ ] Don't delete the whole editor when a rich/video is posted (I just forgot the index param for now)
 - [ ] Delete the link once the content is loaded
 - [ ] Try to wrap the pasted HTML in an iframe to fix several problems (most notably chance of XSS attacks and hopefully being able to have scripts and blockquotes show properly within quill; try https://api.instagram.com/oembed/?url=http://instagram.com/p/V8UMy0LjpX/ to see the issue)
