### ISSUE TITLE
[BUG] Cannot save a query

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#401]
# 🐜 Bug Report

I tried to save a query (search result) but it does not do anything when I hit the save button.

## 📦 Package / Application

@sensenet/sn-app

## 📃 Version

latest

## 🐜 Describe the bug

If i hit the save button on the modal window it does not do anything. On the console I can see some errors related to the missing user profiles, since the action is try to save the non-public queries into the current users user profile.

![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/93bdfd34-e890-44f2-a485-e993c0fe9e44)

Part of the issue cannot be solved since the user profile feature is not the part of the latest sensenet service. 

## 👉 Steps To Reproduce

1. Go to [admin.sensenet.com](https://admin.sensenet.com)
2. Login with Builtin\admin password: admin, repositoryurl: https://dev.demo.sensenet.com
3. Write the query into the command palette ```+TypeIs: Article``` and choose 'Open in search'
4. Click on save query
5. Push the save button

## 😯 Current behavior

Nothing happens, no save, no modal close...nothing

## 🤔 Expected behavior

I think since the user profile feature is not in the sensenet service package and the demo install, 'public' checkbox is unnecessery on the modal. The queries could be saved only as public queries so it should by set by default to true. As I see now, even if I choose to save the query as public it does nothing so, this part of the issue should be also investigated and fixed.

[here](https://github.com/SenseNet/sn-client/blob/master/apps/sensenet/src/components/search/index.tsx#L197-L200) the FormLabel could be removed completely and [here](https://github.com/SenseNet/sn-client/blob/master/apps/sensenet/src/components/search/index.tsx#L207) the action should be called on the current content /context not on the current users profile path (the ```SaveQuery``` action choose where to save it by the ```queryType``` param).

**Comment by atomanonymous** [comment]
I'll work  on this!

**Comment by atomanonymous** [comment]
can u help me bit on the second requirement ?

**Comment by herflis** [comment]
Hi @atomanonymous the second requirement is to 
- [ ] remove the ```repo.authentication.currentUser.getValue().ProfilePath``` from the idOrPath param and
- [ ] set the ```queryType``` simply to 'Public' (so the statement can be removed)

you can find these [here](https://github.com/SenseNet/sn-client/blob/master/apps/sensenet/src/components/search/index.tsx#L207)
