### ISSUE TITLE
Move sn-react-typescript-boilerplate inside the monorepo

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-client#402]
Right now the [sn-react-typescript-boilerplate](https://github.com/SenseNet/sn-react-typescript-boilerplate) is in a separate repository which adds extra steps to upgrade the packages there as well.

We should move it inside the sn-client repository.

Tasks:

- [x] Create a folder named sn-react-typescript-boilerplate under examples folder
- [x] Copy the relevant files to there (src,test, .gitignore, LICENSE, README.md, index.html, package.json, tsconfig.json, webpack.config.js)
- [x] Remove devDependencies that are not needed (eslint related packages, enzyme related packages, husky, lint staged)
- [x] Upgrade to latest version of sensenet scoped packages
- [x] Remove fields that are not needed from package.json (husky, lint-staged, jest)
- [x] Edit tsconfig.json to extend from the tsconfig-base.json from the sn-client root
- [x] Try to run it & build it
- [x] Edit articles that references [sn-react-typescript-boilerplate](https://github.com/SenseNet/sn-react-typescript-boilerplate) in [sensenet.github.io](https://github.com/SenseNet/sensenet.github.io)

**Comment by sumirart** [comment]
Hello @B3zo0
I would like to try to fix this issue, but I don't quite understand these 2  tasks:
* [ ]  Edit tsconfig.json to remove from the tsconfig-base.json from the sn-client root
* [ ]  Edit articles that references [sn-react-typescript-boilerplate](https://github.com/SenseNet/sn-react-typescript-boilerplate) in [sensenet.github.io](https://github.com/SenseNet/sensenet.github.io)

Could you explain more? Thanks!

**Comment by B3zo0** [comment]
Hi @sumirart 

The first one was a typo. I meant to write extend instead of remove.
The second task you mentioned is that in the linked repository if you search for sn-react-typescript-boilerplate you will see that it is used in 3 places. Two in tutorials and in the footer.
The task is to remove it from the footer and update the tutorials with something like. "For references how to create a login form with sensenet see[_new place of the package_]."
