### ISSUE TITLE
Edit sn-react-typescript-boilerplate to use sn-hooks-react

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-client#403]
Once #402 is done, we should rewrite it to use sn-hooks-react.

- [x] Replace useRepository with useRepository from `@sensenet/hooks-react`
- [ ] Add `@sensenet/hooks-react` to package.json and to the tsconfig.json

**Comment by Ishaan28malik** [comment]
Hey I would like to work on this @B3zo0 
But not sure where to implement this change?

**Comment by B3zo0** [comment]
Fixed in #415
