### ISSUE TITLE
Build a GatsbyJS example site powered by sensenet

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#409]
It would be nice is a GatsbyJS expert could helps us try to build a site based on content in a sensenet repository.
You don't have install sensenet, you can use our [demo repository](https://dev.demo.sensenet.com) - check the content of this demo site [here](https://www.sensenet.com/try-it/1000-content-demo)
We don't know yet how we can help you to achieve this but feel free to ask, we are really happy to help you to learn the necessary things about sensenet.

**Comment by sumitkharche** [comment]
Can you please elaborate more on what exactly we have to build using GatsbyJS?

**Comment by mathagician** [comment]
@herflis I would like to work on this.
