### ISSUE TITLE
[admin-ui] Repository chooser revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#422]
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/898210e4-4a4d-4e07-870c-f2fd3b0c11d7)

**Comment by CsabaPeter** [comment]
![Content Dark.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/a1fbc2ec-4269-4cc2-a7c2-2c61ea54c428)

**Comment by CsabaPeter** [comment]
![image.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/9160d8b1-bc13-46c6-84c6-e4b711ecbffa)
