### ISSUE TITLE
Move example apps from sn-panda org to the monorepo

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#445]
- [x] old react todoapp should be removed
- [x] create a netlify site for all the apps

## Example apps to move

- [x] [sn-miniapp-tasklist](https://github.com/sn-panda/sn-miniapp-tasklist)
- [x] [sn-miniapp-usersearch](https://github.com/sn-panda/sn-miniapp-usersearch)
- [x] [snbrowser](https://github.com/sn-panda/snbrowser)
- [x] [snimageupload](https://github.com/sn-panda/snimageupload)
- [x] [sncalendar](https://github.com/sn-panda/sncalendar)
- [x] [snmemoapp](https://github.com/sn-panda/snmemoapp)
- [x] [snimagegallery](https://github.com/sn-panda/snimagegallery)

## Process
- checkout example app locally. Use master branch.
- copy sn-react-typescript-boilerplate in the examples folder
- rename the newly copied sn-react-typescript-boilerplate to the name of the example app. Use our convention, sn-react-{name( without miniapp)}
- copy the src and test folders from example to the new folder in sn-client/examples
- edit readme.md - remove paragraph that are related to the starter
- edit package.json
  - change name
  - add a [contributors](https://flaviocopes.com/package-json/#contributors) section with name and email
  - change keywords if needed
  - add dependencies that needed for example app
- edit public/index.html - change the title and description
- checks
  - start the application with `yarn workspace @sensenet/calendar start` - fix errors that are show in the error overlay
  - run tests with `yarn test examples`
  - run lint with `yarn lint`
- commit and push 🍺

**Comment by pusztaienike** [comment]
Netlify sites:
https://sn-react-imageupload.netlify.com
https://sn-react-imagegallery.netlify.com
https://sn-react-memoapp.netlify.com
https://sn-react-calendar.netlify.com
https://sn-react-browser.netlify.com
https://sn-react-tasklist.netlify.com
https://sn-react-usersearch.netlify.com
