### ISSUE TITLE
[BUG] Upload seems to be successful but the file is not uploaded

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#449]
# 🐜 Bug Report

Upload progress indicates that the file was uploaded successfully, but it does not listed in the folder. There's a 'types is not allowed here' error is on the console and it seems that the progress indicator does not check these kind of error messages.

## 📦 Package / Application

@sensenet/sn-app

## 📃 Version

latest

## 👉 Steps To Reproduce

1. Go to admin.sensenet.com and login with admin
2. Create a DemoWorkspace into /Content 
3. Add a folder to the demoworkspace
4. Upload an image into the folder
5. If the upload progress is completed close the upload modal
6. The current content is not the folder as it was selected before but its parent ws
7. If you open the folder you can see that the uploaded file is not there
8. Check the browser console for the error message

```
{
  "error": {
    "code": "NotSpecified",
    "exceptiontype": "Exception",
    "message": {
      "lang": "en-us",
      "value": "A content of this type cannot be created here."
    },
    "innererror": null
  }
```

## 🤔 Expected behavior

The upload progress indicator should not displayed as completed since the file is not completely uploaded.
There should be the error message displayed on the upload modal.

**Comment by B3zo0** [comment]
Note: 
get error from response with `repository.getErrorFromResponse`
https://github.com/SenseNet/sn-client/blob/c40c3985b3d6076e355f35ef88c66b4c61dd47ac/packages/sn-client-core/src/Repository/Upload.ts#L217
