### ISSUE TITLE
[admin-ui] Edit/New/Browse (info) view revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#488]
- [x] Revise the current design
- [x] Remove the Edit/New/Browse views' dialog version from the style guide
- [x] Place full Path somewhere on the dialog, to let the users copy it
- [x] Place the type icon/avatar somewhere on the dialog and make it clickable and navigate user to the current content's content type defintion when user click it.
- [x] Create 'full screen' version screen of the version history
- [x] Before saving the offline styleguide, please make sure that the position of the tree is fixed
- [x] Save an offline version of the styleguide

current browse dialog of a ws:

![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/5ef6b291-5573-4b47-8db3-05f97578927a)

old version history page:
![image](https://user-images.githubusercontent.com/6968860/72874383-2b093f80-3cf2-11ea-8be6-d48163638988.png)

**Comment by CsabaPeter** [comment]
Offline: P:\Products\SenseNet-CMS\SNaaS\Field controls
Online: https://xd.adobe.com/view/0da9e275-588c-451a-64c2-7a3b1c3d9933-7b98/

**Comment by CsabaPeter** [comment]
Updated the screens
