### ISSUE TITLE
[BUG] Name is 'undefined' after editing a content

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#512]
Steps to reproduce:
1. Login with businesscat at admin.sensenet.com
2. Go to an image library and open an image to edit
3. Change some field values and click on Save

![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/76803db0-bb2f-4bc5-a736-7cea26b7906c)

**Comment by pusztaienike** [comment]
Cannot reproduce
