### ISSUE TITLE
[admin-ui] Create a new usermenu component based on the new styleguide

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#518]
[https://xd.adobe.com/view/401d55f2-8eb5-48cb-7e4c-cddb651ca03d-362c/screen/530b0d32-2ce4-4cd0-88c5-da4eabe13dbf/Admin-light](https://xd.adobe.com/view/401d55f2-8eb5-48cb-7e4c-cddb651ca03d-362c/screen/530b0d32-2ce4-4cd0-88c5-da4eabe13dbf/Admin-light)

**Comment by pusztaienike** [comment]
Already implemented in https://github.com/SenseNet/sn-client/pull/525
