### ISSUE TITLE
[spike] Try out authentication in an asp.net web app with js

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#541]
goal: find a standard way to login with js (how a request should look like, what we have to get in the response, etc)

**Comment by B3zo0** [comment]
- [ ] We need a configuration ([Discovery](http://docs.identityserver.io/en/latest/endpoints/discovery.html)) endpoint to get the right authority from the backend (sensenet)

- [ ] We may want to customize the login, logout, manage pages in our identity server

- [ ] We have to rework the login page in admin-ui to match with the new workflow

- [ ] Think about backward compatibility? Once we move to IdentityServer4 are we going to support older versions of sensenet with forms authentication?

- [ ] Is this implementation browser only?
