### ISSUE TITLE
[BUG] The marital status of user(s) can be Married & Single at the same time

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#543]
# 🐜 Bug Report

We should limit the UI for only one choice 
-> E.g: if user click on "Married" it should be checked, and the other 2 possible item should be unchecked

![image](https://user-images.githubusercontent.com/22347393/72070354-ae399700-32e9-11ea-9cee-6d85cd418ffb.png)

## 📦 Package / Application

admin-ui

## 👉 Steps To Reproduce

1. Login with admin on admin-ui
2. Click on Users & group drawer item
3. Select a user (eg. businesscat)
4. Tick both 3 checkboxes under Marital status field

## 😯 Current behavior

You can tick both 3 checkboxes under Marital status field.

## 🤔 Expected behavior

You can tick only 1 checkbox under Marital status field.

**Comment by herflis** [comment]
@pusztaienike it was a permanent thing while i showed @CsabaPeter a choice field with AllowMultiple prop set to true 😃
