### ISSUE TITLE
[FEATURE] In commander view distinct the active side somehow

### ISSUE THREAD

**Issue by zoltanbedi** [SenseNet/sn-client#544]
## 📦 Package / Application
snapp

## 🤔 Expected Behavior
I expect a behavior like in total commander

## 😯 Current Behavior
Right now I don't know which side is active when I browse content in commander view.

**Comment by pusztaienike** [comment]
Commander should be removed, so I close this issue related to https://github.com/SenseNet/sn-client/issues/681
