### ISSUE TITLE
[BUG] Navigate to login view once session times out

### ISSUE THREAD

**Issue by zoltanbedi** [SenseNet/sn-client#556]
# 🐜 Bug Report

Once the users session times out we should navigate the user to login page once they tries to do something in the admin ui.

## 📦 Package / Application

sn-app 1.4.1

## 👉 Steps To Reproduce

1. Log in with businesscat
2. Remove .ASPXAUTH cookie
3. Try to navigate in the tree

## 😯 Current behavior

Screenshot below

## 🤔 Expected behavior

We should navigate the user to login page

## 🖼 Screenshots

![sensenet - Google Chrome 2020-01-17 12_30_11](https://user-images.githubusercontent.com/13729989/72609694-e1051000-3925-11ea-9592-7b3d5cd579eb.png)

**Comment by B3zo0** [comment]
Let's review this once #568 get merged.
