### ISSUE TITLE
[FEATURE] [document-viewer-react] Comments section

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#56]
# 🙋 Feature Request

As an end user, when previewing content, I would like to use a comments section that displays comments so that I can view and participate in the discussion about the specific page I see. I don't need replies.

## 📦 Package / Application

@sensenet/document-viewer-react

## 📃 Version

1.0.4

## 😯 Current Behavior

No commenting function in present version.

### Layout

* Comments section in right sidebar displays comments belonging to the page where their marker is placed.
* All comments have one marker, displayed on the page.
* Switch button is fixed in top right position in menu bar. It displays/hides markers and comments. By default, they are displayed.
* Already saved comments boxes contain: avatar, display name, text.
* Comments are listed in the comment section in the order defined by their marker’s vertical and horizontal positions.
* Comments are displayed under each other, and not at their markers vertical position.

### Behavior

* If there are too many comments, user can scroll comment section to see all comments belonging to the page.
* If user clicks a marker, system visually differentiates related comment, and if needed, scrolls comments section so that comment becomes visible for the user.

### UX

* [Design](https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flitvanyia_sensenet_com%2FDocuments%2Fsn%2Fux%2FDocviewer%20desktop%2FDocviewer%2FVegleges%20UI)
* [Proto](https://xd.adobe.com/view/e71214ce-b867-4821-5ee7-4c1c5c685a9e-9123/)

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments in DocViewer](https://trello.com/c/H68guu6E/2-comments-in-docviewer)
