### ISSUE TITLE
[admin-ui] Repository/user dashboard revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#560]
- [x] Check the dashboard of the main competitors -> [here](https://teams.microsoft.com/l/channel/19%3Ac3c2e4bfb90348ada6b10a880adf1333%40thread.skype/tab%3A%3A0833a058-d6b4-47b0-83d9-8e5d8202479c?groupId=c84dc3aa-77d5-47f7-90a2-7f6b6b8178d9&tenantId=6069be31-3d96-48fc-af43-2ed5a1538540)
- [x] Make a list of the necessary/unnecessary infos/widgets
- [x] Create multiple versions of design for both two themes and demo sites/subscription plans

**Comment by herflis** [comment]
demo 1
- [ ] number of users 1/3
- [ ] storage space 2,5/10GB
- [ ] number of content 133/1000
- [ ] version info and upgrade details
	- [ ] developer plan (free)
	- [ ] versionnumber 7.7.7

demo 2
- [ ] number of users 3/3
- [ ] storage space 9,8/10GB
- [ ] number of content 967/1000
- [ ] version info and upgrade details
	- [ ] developer plan (free)
	- [ ] versionnumber 7.7.7

demo 3
- [ ] number of users 7/25
- [ ] storage space 11,2/25GB
- [ ] number of content 2333/25000
- [ ] version info and upgrade details
	- [ ] business plan (expire on 2020.12.20)
	- [ ] versionnumber 7.5.0

demo 4
- [ ] number of users 7858
- [ ] storage space 235,5GB
- [ ] number of content 4232481
- [ ] version info and upgrade details
	- [ ] enterprise plan (expire on 2020.11.12)
	- [ ] versionnumber 7.17.2

**Comment by CsabaPeter** [comment]
![Dashboard Dark.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/8b9aa515-da6a-42a4-9aa2-2ea812f52f8d)
![Dashboard Light.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/a46e2da7-5418-4ff1-b013-482d4f74c852)

**Comment by herflis** [comment]
- [ ] try to merge the top two boxes to demonstrate that the upgrade is necessary because you reached the limits (user, content, etc), so let's see how it works if theres a common right column, with the upgrade part (title, desc, button)
- [ ] if a limit is close and one of the progressbars are red/yellow, the upgrade button could have the same color
- [ ] instead of the 'upgrade here' link, there should displayed the date of the next upgrade (after a release will be published, there will be a short intervall till the actual upgradte) 
- [ ] stuff that is close to a limit should be marked with something (icon, image, something) besides it has a different color
- [ ] please change the images at the documentation links to a simple icons, or animals
- [ ] in the light theme there's a grey background behind the doc links, let's see how it looks if all the boxes have the same background (grey)
- [ ] it is not related but it will be nice if the light theme would work the same as the dark in the background coloring of the drawer and the header. In the light theme now everything is white, which kills the eyes 😎
