### ISSUE TITLE
[BUG] Crash the useRepositoryEvents hook in the production build

### ISSUE THREAD

**Issue by blaskodaniel** [SenseNet/sn-client#562]
# 🐜 Bug Report

I use the CurrentContentProvider context in my application. When I use in the develop mode then it works fine, but I want to use it in the production build the useRepositoryEvents hook (in CurrentContentProvider) will be crashed with this error:

> TypeError: Cannot read property 'isTraced' of undefined
>     at Function.value (trace.ts:217)
>     at e.value (EventHub.ts:136)
>     at new e (EventHub.ts:130)
>     at Object.t.useRepositoryEvents (use-repository-events.ts:11)
>     at t.CurrentContentProvider (current-content.tsx:38)
>     at ua (react-dom.production.min.js:154)
>     at Os (react-dom.production.min.js:259)
>     at ml (react-dom.production.min.js:230)
>     at hl (react-dom.production.min.js:229)
>     at ol (react-dom.production.min.js:223)

## 📦 Package / Application

useRepositoryEvents() hook

## 🖼 Screenshots
![client-library issue-istrcaed](https://user-images.githubusercontent.com/22953736/73179722-3f937080-4114-11ea-9c41-a05a8ea04293.jpg)

**Comment by B3zo0** [comment]
This is fixed in https://github.com/SenseNet/sn-client/pull/563
