### ISSUE TITLE
[BUG] Opening actionmenu on a content requires two clicks

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#567]
The actionmenu can be opened two ways, right clicking on a grid row, or clicking on the icon in the last column. Both ways working only if the user selected the item before (e.g. the user should click twice, once to select the item, and twice for open the actionmenu.) Since the user thinks after one click that it is not working she leaves the grid immediately.

![](https://s5.gifyu.com/images/open-actionmenu.gif)

Please fix this issue by handling content selection and opening the actionmenu with right click/click on the '...' icon at once.

**Comment by pusztaienike** [comment]
#539 solves this --> but the right-click action is not implemented yet in the virtualized table
