### ISSUE TITLE
[admin-ui] Progress indicator

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#569]
As we decided earlier we change the giant sn logo to [material-ui linear progress indicator](https://material.io/components/progress-indicators/#linear-progress-indicators), so please add a some examples of that to the styleguide.

**Comment by CsabaPeter** [comment]
Can be a circular progress indicator with "loading content".
![Loading Dark.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/06cf05a9-c511-4fa1-a6bc-058a92ab660f)
https://material-ui.com/components/progress/

**Comment by CsabaPeter** [comment]
The color of the circular progress indicator should be #26A69A both in dark and light theme.
