### ISSUE TITLE
[FEATURE] [document-viewer-react] Add comments

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#57]
# 🙋 Feature Request

As an end user, when previewing content, I would like to add comments in the comment section next to the page of the content I'm previewing.

## 📦 Package / Application

@sensenet/document-viewer-react

## 📃 Version

1.0.4

## 😯 Current Behavior

No commenting function in present version.

## 💁 Possible Solution

* User clicks +Add comment button (fix or floating)
* After the click the system waits for the user to place a marker somewhere on the page (ESC aborts)
* After user has placed the marker: the new comment box appears with avatar and textbox in it. The new comment is added to the page’s comment list depending on the new marker’s position (to the top or bottom of the list, or inserted at a position within the list.)
* User types text, clicks Submit.
* New comment is saved.

### UX

* [Design](https://sensenet-my.sharepoint.com/personal/litvanyia_sensenet_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flitvanyia_sensenet_com%2FDocuments%2Fsn%2Fux%2FDocviewer%20desktop%2FDocviewer%2FVegleges%20UI)
* [Proto](https://xd.adobe.com/view/e71214ce-b867-4821-5ee7-4c1c5c685a9e-9123/)

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments in DocViewer](https://trello.com/c/H68guu6E/2-comments-in-docviewer)

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments in DocViewer](https://trello.com/c/H68guu6E/2-comments-in-docviewer)
