### ISSUE TITLE
[admin-ui] Modify ctd save to handle when the user changes the content type name or the parent type

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#571]
If the user changes the name of the content type or the parent type the ctd should be saved as a new one. Now we try to save (upload) the file as the opened one and it occures an error, so we have to get the info from the monaco editor if the user changed the value of the content type name or the parent type name and do the following:

- [ ] If the parent type name is changed, the parent path where the upload request is sent have to be updated
- [ ] If the content type name is changed, the file should be uploded with the new name

This way the repository will handle the situation on the server and in the end a new ctd content will be created.

**Comment by tusmester** [comment]
Revisit this when we start working on the CTD editor.
