### ISSUE TITLE
[BUG] Office online view mode does not show changes

### ISSUE THREAD

**Issue by blaskodaniel** [SenseNet/sn-client#584]
After editing the document with office online I can't see my changes in view mode.

Additional info about a somewhat similar issue (maybe it helps the investigation):

When a user edited a document and restored it to its previous version the file after downloading it remains same, edited version not the restored one. In .net application the restored previous version is downloaded perfectly. When we open the same document in react application, instead of restored version it is coming with latest (modified) version.
Only the difference is in .net application we downloaded the file and checked out, in react application instead of downloading the file we tried to open the same file in office online.

## 📦 Package / Application
snapp 1.4.3

## 👉 Steps To Reproduce

1. Go to https://admin.sensenet.com/
2. Edit a .docx file with office online
3. Change the back of the url from `/wopi/<contenId>/edit` to `/wopi/1506/view`

The changes are not in the read/view mode.

 ../edit/contentID/edit
![image](https://user-images.githubusercontent.com/22953736/75683893-33ad4800-5c98-11ea-8b17-9dcf9ec13cf4.png)

.../edit/contentID/view
![image](https://user-images.githubusercontent.com/22953736/75683969-4fb0e980-5c98-11ea-899a-b8dff54ca219.png)

**Comment by sreekanthedayar** [comment]
We also encountered a same issue. We tried to edit a file in office online. saved it and then restored to a older version, then again open it in office for online editing but it is showing latest version and not the restored version.

**Comment by tusmester** [comment]
We've identified the problem, working on it.

**Comment by herflis** [comment]
@blaskodaniel thanks for reporting this issue. The fix is now published with the [latest release](https://community.sensenet.com/releases/2020/05/04)

**Comment by herflis** [comment]
@sreekanthedayar thanks for mentioning that you're also encountering the same issue. The fix is now published with the [latest release](https://community.sensenet.com/releases/2020/05/04)

**Comment by sreekanthedayar** [comment]
Thanks @herflis for this. Hope we can upgrade with out compatibility issues. will this upgrade breaks any current features?
