### ISSUE TITLE
[admin-ui] Batch operations

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#589]
There are several actions that can be executed on multiple items like delete, copy or move. Multiple selection is already available, but the batch actions are missing. Lets find out where would be their place on the ui.

Examples:
- old sensenet content explorer: actions are disabled till a content or more is selected
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/80927fa3-c15a-4b3d-ae1b-be363c9a74dc)
- dms: actions are hidden till a content or more is selected
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/ed317873-8f34-4e04-8e28-8739132e252f)
- contentful: not the same feature but worth mentioning
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/edbed489-7497-41ce-8446-0e3f264b18da)

**Comment by CsabaPeter** [comment]
https://xd.adobe.com/view/029b825d-5377-46b0-7a97-31a27df98da2-74aa/
