### ISSUE TITLE
[admin-ui] Notifications

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#590]
There're cases when too many notifications come up or when they do not disappear and hide the important part of the screen. However also the notifications' content, location and visibility, etc (importance in some cases) should be revisited, lets see if we can improve something by changing only size of the notifications or move them where they are not so distracting.
- [x] check other products' (not necessarily cms') soliution for notifications
- [x] what type of notifications should be on admin-ui (error, warning, info?)
- [x] how the different type of notifications should be displayed and work (disappear after a while or have to be manually closed)
- [x] where should notifications appear?

**Comment by herflis** [comment]
In the case of the admin-ui there're 2 scenarios when we should display notifications
- an operation is successfully done (content creation, modification, permission setting, etc) on one or multiple content
   - this is a medium attention scenario
- an operation cannot be executed on a content (in this scenario we also have an error message)
   - this is a high attention scenario

**Comment by CsabaPeter** [comment]
I did a two samples which resembles to the format that we already been using but I added a close icon and so if the user wnats to close the notification before it disappears he can do it so it will still highly wisible but the user don't have to wait.

We should think of some one line error messages in those scenarios where the error message is one big line of code which covers half the screen.

![Fail](https://user-images.githubusercontent.com/38352683/93215216-64515c80-f766-11ea-8b10-90e5f7222502.png)
![Success](https://user-images.githubusercontent.com/38352683/93215224-674c4d00-f766-11ea-9684-24aa3e74d064.png)

**Comment by CsabaPeter** [comment]
https://miro.com/app/board/o9J_kofCIrk=/
