### ISSUE TITLE
Problems with spacing between columns when Sidebar is opened

### ISSUE THREAD

**Issue by CsabaPeter** [SenseNet/sn-client#597]
When the browser is not in fullscreen, the sidebar is opened and the user is in the content types, the first column slides over to the second.
![Screen Shot 2020-03-16 at 15.43.31.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/c5b259e8-3fe1-488c-b371-6ff0a37fffb3)

**Comment by pusztaienike** [comment]
It has been already fixed.
