### ISSUE TITLE
Objects in opened sidebar slides together

### ISSUE THREAD

**Issue by CsabaPeter** [SenseNet/sn-client#607]
Some objects in the sidebar when it's opened slides together when the Admin Ui is not fullscreen
![Screen Shot 2020-03-27 at 11.38.42.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/284527a2-1fca-4afe-ba4f-eb5a1ad58bcc)
![Screen Shot 2020-03-27 at 11.38.30.png](https://images.zenhubusercontent.com/5ad745c94b5806bc2bcf9d21/e16edda3-e190-47d0-8393-610c3614b444)

**Comment by pusztaienike** [comment]
We could not reproduce this issue.
