### ISSUE TITLE
Change the style of error messages on Identity server

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#679]
# 🙋 Feature Request

The error messages are not fit to the actual design on the login form.

![image](https://user-images.githubusercontent.com/22347393/82544198-0e243200-9b55-11ea-8bd1-8ba18c4e323f.png)

Should have a new design for this, and implement it on IS

- [x] New design
- [x] Implementation
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver/pullrequest/36?_a=overview

## 📦 Package / Application

IS4 - Login site

## 📃 Version

Identity server repo : https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver

**Comment by tusmester** [comment]
Maybe we could put the error message closer to where it occurs - e.g. the text boxes and the button :).

**Comment by CsabaPeter** [comment]
https://xd.adobe.com/view/55827705-66a0-4bae-4e1b-94a90b7f7643-23b3/
