### ISSUE TITLE
[snaas] Design thank you+confirm email screen

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#709]
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/27a23c41-6d10-41cc-ba3f-7a9a74e49e2f)

The actual view is here:/Views/Account/ConfirmEmailSent.cshtml

[for inspiration](https://dribbble.com/search/confirm%20email)

PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/sn-identityserver/pullrequest/36?_a=overview

**Comment by CsabaPeter** [comment]
https://miro.com/app/board/o9J_kqQtbA8=/
