### ISSUE TITLE
[snaas] Login form of the different identity servers

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#713]
There're now two Identity Servers to demonstrate snoversn and user repository login and registration separately. 

is.sensenet.com is the snaas server so it is for login and registration for the snaas users (only **sensenet** is the user that is automatically added with the install)
is.demo.sensenet.com is connected to the demo repositories (dev.demo, business.demo, sales.demo) (demo users are like businesscat and devdog are added with the install)

The first one should not have the login to the demo option 

##### Followings should be changeable/configurable:
- [ ] favicon
- [ ] site title
- [ ] logo
- [x] registration
- [x] 'welcome' text
- [x] demo user/repo section
- [x] login to another repository button
- [ ] social logins section

**Comment by huszerlbence** [comment]
We should include beta info to the live registration/login page.
the displayed message should be the following:

Please note that SNaaS is running in beta until 31.12.2020. We are eager to hear your feedbacks to improve the service. During the beta period business plan subscribers can enjoy the service for free in 2020.

**Comment by herflis** [comment]
A separate issue was made for the remaining tasks [here](https://github.com/SenseNet/sn-client/issues/994)
