### ISSUE TITLE
[E2E test] Drawer open/close

### ISSUE THREAD

**Issue by CsabaPeter** [SenseNet/sn-client#746]
# 🧪E2E test cases

The scope of these tests is to ensure that the drawer opens and closes successfully.

<img width="243" alt="Screen Shot 2020-07-21 at 4 28 31 PM" src="https://user-images.githubusercontent.com/38352683/88067668-916efd80-cb6f-11ea-872d-5c2f414872e1.png">

# Test case 1

## 😎 Role

All test should run as admin.

## 🧫 Purpose of the test

Click on the hamburger menu (the 3 lines on the top of the drawer) icon should open the drawer and the user should see an extended view of the icons with descriptions.

## 🐾 Steps

1. Login with admin role
2. Click the hamburger menu icon on the drawer

## Expected result

Drawer opens

# Test case 2

## 😎 Role

All test should run as admin.

## 🧫 Purpose of the test

Click on the X icon should close the extended view of the drawer.

## 🐾 Steps

1. Login with admin role
2. Click the hamburger menu icon on the drawer
3. Click the X icon to close the extended view

## Expected result

Drawer Closes

**Comment by daniel-shuy** [comment]
I'll take this task, please assign it to me

**Comment by herflis** [comment]
Hi @daniel-shuy ,  did you manage to deal with this? Is there anything we can help you with? :)

**Comment by daniel-shuy** [comment]
hi @herflis, thanks for checking up on me, I was initially confused by which module this was supposed to be for (as running Cypress from root ran the tests for the `sn-dms-demo`). Just figured out that the test should be for the `apps/sensenet` module, should be easy from here on :)

**Comment by herflis** [comment]
I'm glad to hear that @daniel-shuy ! Don't forget to request a sensenet repository [here](https://profile.sensenet.com/?redirectToLogin) for yourself, you can get an extra hacktoberfest swag and also it makes writing tests easier. :)
