### ISSUE TITLE
🧪[E2E test] Add Cypress test - Switching themes

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#749]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the theme switcher is working properly.

![image](https://user-images.githubusercontent.com/6968860/88139608-57920b80-cbf0-11ea-8e43-49906d6cf38e.png)

# Test case 1

## 😎 Role

All test should run as **admin**.

## 🧫 Purpose of the test

The default theme should be light.

## 🐾 Steps

  1. Login with admin role
  2. Open the user menu next to the user avatar

## Expected result
  The theme-switcher's text is _'Dark theme'_ and the switcher is not **'checked'**

# Test case 2

## 😎 Role

All test should run as **admin**.

## 🧫 Purpose of the test

Purpose of this text is to ensure that clicking the theme-switcher changes the theme.

## 🐾 Steps

  1. Login with admin role
  2. Open the user menu next to the user avatar
  3. Click on the theme-switcher

## Expected result
  The theme-switcher's text is _'Light theme'_ and the switcher is **'checked'**

**Comment by aslafy-z** [comment]
I'd like to work on this issue, can you assign it to me? Thank you

**Comment by aslafy-z** [comment]
Sorry for the delay, I'd like to finish my related PR. Can you assign me back? Thank you
