### ISSUE TITLE
[snaas-profile] Finalize plan name link

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#765]
![image](https://user-images.githubusercontent.com/6968860/89181291-af872580-d593-11ea-86c4-fccc1dcd31be.png)

Plan name link should navigate to the related plan's description (pricing or plans page) on sensenet.com

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/70?_a=overview
