### ISSUE TITLE
[snaas-profile] Closed invoice page

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#772]
Caused by the "open single invoice" option we should create another view for completed (closed) items.

Amount to be payed
649 USD

we should change the amount -> Settled (649 USD)

"Settled" should be green and bold

Due date should contain original due date of the invoice w/o any further status (like expired, completed)

![image](https://user-images.githubusercontent.com/6968860/89196034-f08a3480-d5a9-11ea-8dfe-3abb6f2e8a9f.png)

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/130?_a=overview
