### ISSUE TITLE
[E2E test] Add Cypress test - AddNew menu

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#776]
# 🧪E2E test cases

The scope of these tests is to ensure that the AddNew menu works as it is intended.
![image](https://user-images.githubusercontent.com/22347393/89291843-89c55380-d65b-11ea-8774-a144d850cc5c.png)

# Test case 1

## 😎 Role

All test should run as admin.

## 🧫 Purpose of the test

Click on the AddNew button should open a dropdown with the list of allowed child types.

## 🐾 Steps

1. Login with admin role
2. Click on 'Content' menuitem
3. **Step**: Click on AddNew button
**Expected result:** The following items are available on the dropdown:
- Folder
- Document Library
- Image Library
- Event List
- Memo List
- Link List
- Task List
- Custom List
- Workspace
- System Folder
- Demo Workspace

# Test case 2

## 🧫 Purpose of the test

After select one item from the dropdown an editor of the new content should be appeared and AddNew button should be disabled

## 🐾 Steps

1. **Step**: Select Folder item from the dropdown
**Expected result:** 
The editor of the new content appears with the title: 'New Folder'
The AddNew button should be disabled
2. Click on Cancel button

**Comment by RanadeepPolavarapu** [comment]
I can work on this.

**Comment by herflis** [comment]
Thank you @RanadeepPolavarapu ! You can find all the related info about sensenet hacktoberfest [here](https://hacktoberfest.sensenet.com/). I strongly recommend you to check this [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) before you start. :) Let us know if need help!
