### ISSUE TITLE
[E2E test] Add Cypress test - Tree

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#793]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the Tree component works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/90527668-14d13e00-e172-11ea-87bb-311ef36e512d.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

Click on the Tree item should open with the list of its children.

## 🐾 Steps

1. Login with admin role
2. Click on 'Content' menuitem
3. **Step:** Click on IT Workspace tree item
    **Expected result:** The following items appear under the IT Workspace tree item as children:

- Calendar
- Document Library
- Groups
- Links
- Memos
- Tasks
- Image Library

# Test case 2

## 🧫 Purpose of the test

Click on the Tree item when it is open should close it and make its children invisible.

## 🐾 Steps

1. **Step:** Click on IT Workspace tree item (when it is open)
    **Expected result:** The children of IT Workspace tree item should be invisible.

# Test case 3

## 🧫 Purpose of the test

Right click on the Tree item should make context-menu open.

## 🐾 Steps

1. **Step:** Right click on IT Workspace tree item
    **Expected result:** The context-menu dropdown should be visible with the following actions:

- Browse
- Copy to
- Edit
- Move to
- Versions
- Share
- Delete
- Set permissions

2. Click away

**Comment by NileshPatel17** [comment]
For my repo, i did not have following items under "IT Workspace", hence used "Sample workspace",

    Calendar
    Document Library
    Groups
    Links
    Memos
    Tasks
    Image Library

<img width="452" alt="Screenshot 2020-10-31 at 11 37 53 AM" src="https://user-images.githubusercontent.com/27020381/97772495-c676ed00-1b6d-11eb-91d9-478aa0e1f440.png">

**Comment by NileshPatel17** [comment]
@herflis please assign it to me.
