### ISSUE TITLE
[E2E test] Add Cypress test - Localization menu

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#795]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the Localization menu works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/90533504-ec007700-e178-11ea-9350-eb8e8797ffde.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that ActionResources.xml is there in the list

## 🐾 Steps

1. Login with admin role
2. **Step:** Click on Localization menu item
**Expected result:** ActionResources.xml is in the list

# Test case 2

## 🧫 Purpose of the test

Right click on a 'localization item' should make context-menu open.

## 🐾 Steps

1. **Step:** Right click on ActionResources.xml item
**Expected result:** The context-menu dropdown should be visible with the following actions:

- Browse
- Copy to
- Edit
- Move to
- Versions
- Check out
- Share (disabled)
- Delete
- Set permissions
- Download

2. Click away

# Test case 3

## 🧫 Purpose of the test

Double click on 'localization item' should open a binary editor with the content of the item .

## 🐾 Steps

1. **Step:** Double click on ActionResources.xml item
**Expected result:** A binary editor has appears with the content of ActionResources.xml  on a new page. The page should contain the name of the 'localization item' (ActionResources.xml )
2. Click on Cancel

**Comment by dlemstra** [comment]
Tests have been added in this PR: #1023
