### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Breadcrumb

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#796]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the breadcrumb displayed and works as it is intended.

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that breadcrumb after navigating to IT doclib is displayed as it should.

## 🐾 Steps

1. Login with admin role
2. Click on _Content_ menu item
3. Open _IT workspace_ with clicking on it in the tree
**Expected result**: children of _IT Workspace_ are listed (_Calendar_ is the first child item in the grid).
4. Choose _Document library_ from _IT Workspace_'s children and open it
**Expected result**: the breadcrumb contains the following items: Content, IT Worksapce, Document library

![image](https://user-images.githubusercontent.com/6968860/90602697-763cef80-e1fa-11ea-8743-588bc1c5b2f5.png)

# Test case 2

## 🧫 Purpose of the test

To ensure that clicking on parent item in the breadcrumb opens the chosen container.

## 🐾 Steps

1. Login with admin role
2. Click on _Content_ menu item
3. Open _IT workspace_ with clicking on it in the tree
**Expected result**: children of _IT Workspace_ are listed. (_Calendar_ is the first child item in the grid).
4. Choose _Document library_ from _IT Workspace_'s children and open it
5. Click on _IT Workspace_ in the breadcrumb
**Expected result**: children of _IT Workspace_ are listed (_Calendar_ is the first child item in the grid).

# Test case 3

## 🧫 Purpose of the test

To ensure that right click on a breadcrumb item opens its actionmenu.

## 🐾 Steps

1. Login with admin role
2. Click on _Content_ menu item
3. Open _IT workspace_ with clicking on it in the tree
**Expected result**: children of _IT Workspace_ are listed. (_Calendar_ is the first child item in the grid).
4. Choose _Document library_ from _IT Workspace_'s children and open it
5. Right-click on _IT Workspace_ in the breadcrumb
**Expected result**:  Actionmenu is open for _IT Workspace_

![image](https://user-images.githubusercontent.com/6968860/90603253-4e01c080-e1fb-11ea-85b0-20ef63a6559b.png)

**Comment by NileshPatel17** [comment]
@herflis please assign this to me.
