### ISSUE TITLE
🧪 [E2E test] Add Cypress test - New users and groups

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#797]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that user and group creation works as it is intended.

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that user contents are always deleted permanently and are not moved to trash

## 🐾 Steps

1. Open Users&Groups menuitem
2. Right-click on user _Developer Dog_
3. Choose Delete from the dropdown
4. Click on Delete button
5. **Step:** Click on Trash menuitem
      **Expected result:** Trash should not contain _Developer Dog_

# Test case 2

## 🧫 Purpose of the test

The scope of this test is to ensure that creating a new user works as it is expected.

## 🐾 Steps

1. Login with admin role
2. Click on _Users & groups_ menu item
3. Click on the add button at the top of the drawer
**Expected result**: add new dropdown opens
4. Choose _User_ from the dropdown
**Expected result**: User creator view is displayed
5. Fill the following fields:
   - Login name: devdog
   - Full name: Developer Dog
   - Email: devdog@sensenet.com
   - Password: devdog
6. Click on submit button
**Expected results**:
   - User list is opened
   - Item with name _devdog_ is added to the list
   - Notification is displayed that the user is successfully added.

![image](https://user-images.githubusercontent.com/6968860/90605429-9f5f7f00-e1fe-11ea-94e2-4d3ff6bbca2b.png)

# Test case 3

## 🧫 Purpose of the test

The scope of this test is to ensure that creating a new group works as it is expected.

## 🐾 Steps

1. Login with admin role
2. Click on _Users & groups_ menu item
3. Switch to group view with clicking _Groups_ on the switcher
4. Click on the add button at the top of the drawer
**Expected result**: add new dropdown opens
5. Choose _Group_ from the dropdown
**Expected result**: Group creator view is displayed
6. Fill the following fields:
   - Name: test
7. Click on submit button
**Expected results**:
   - Group list is opened
   - Item with name _test_ is added to the list
   - Notification is displayed that the group is successfully added.

![image](https://user-images.githubusercontent.com/6968860/90605771-17c64000-e1ff-11ea-8b96-fad0570d532d.png)

**Comment by arc9693** [comment]
I would like to take this up
