### ISSUE TITLE
🧪 [E2E test] Click on the logo in the header 

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#828]
# 🧪E2E test cases

The scope of this test is to ensure that the link on the sensenet logo works as it is intended.
![image](https://user-images.githubusercontent.com/22347393/91864080-1f123280-ec70-11ea-8410-a77f36b2c837.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that clicking on sensenet icon navigates to the dashboard page.

## 🐾 Steps

1. Login with admin role
2. Click on Content menu item
3. **Step:** Click on sensenet icon (on the header)
    **Expected result:** Dashboard page appears

**Comment by pietervanh** [comment]
Allright this seems to be a good one to get started.
