### ISSUE TITLE
🧪 [E2E test] Add Cypress test -  Content types menu

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#829]
# 🧪E2E test cases

The scope of these tests is to ensure that the Content types menu works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/91865767-030f9080-ec72-11ea-8691-9c116836415b.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that Article is there in the list

## 🐾 Steps

1. Login with admin role
2. **Step:** Click on Content Types menu item
    **Expected result:** Article is in the list

~# Test case 2~

~## 🧫 Purpose of the test~

~Right click on a 'content type' should make context-menu open.~

~## 🐾 Steps~

~1. **Step:** Right click on Article item~
    ~**Expected result:** The context-menu dropdown should be visible with the following actions:~

~- Edit~
~- Delete~
~- Set permissions~

~2. Click away~

# Test case 3

## 🧫 Purpose of the test

Double click on 'content type' should open a binary editor with the content of the item .

## 🐾 Steps

1. **Step:** Double click on Article item
    **Expected result:** A binary editor has appears with the content of Article. The page should contain the name of the 'content type' (Article)

2. Click on Cancel

**Comment by shinnlok** [comment]
@pusztaienike Can I give this a try?

**Comment by herflis** [comment]
Sure, @shinnlok 👍  You can find all the related info about sensenet hacktoberfest [here](https://hacktoberfest.sensenet.com/).  I strongly recommend you to check this [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) before you start. :) Good luck!
