### ISSUE TITLE
[@Sensenet\Query] An alternative to figuring out what the type it is when querying.

### ISSUE THREAD

**Issue by LuisAverhoff** [SenseNet/sn-client#84]
So couple of the functions in the query module make use of the function's name property so it knows what type of content it is querying. This works in development but will fail in production when minified. One can simply pass `keep_fnames: true` to avoid this issue but this would no doubt increase the bundle size by quite a bit. 

A simple solution to this I believe would be to add a static property to all the content types in the module `@sensenet\default-content-types` and reference that property when it comes to querying for the type.

Here is an example

```
export class GenericContent {
  public static TypeName: string = "GenericContent"
  ...Other Properties
}

export class Folder extends GenericContent {
  public static TypeName: string = "Folder"
  ... Other Properties
}
```

Then for example, in the TypeIs function we can do this

```
public typeIs<TNewType>(newTypeAssertion: { new(...args: any[]): TNewType; TypeName: string }) {
    this.stringValue = `TypeIs:${newTypeAssertion.TypeName}`
    this.segmentType = 'typeIs'
    return this.finialize<TNewType>()
  }
```

And now it wont matter if function.prototype.name gets minified. 

Link to demo https://tinyurl.com/ybvuvphg

**Comment by gallayl** [comment]
I understand the problem but I don't think that we should solve it with an additional property.
Here are the my cons: 
 - In that way <TNewType> should have always the new static property - TS support for static generic constraints are also not so straightfowrard
 - The additional property will also increase bundle size, the benefit will be even smaller
 - It would be a big breaking change - not only for the Query and DefaultContentTypes package

I think you should consider one of the following possibilities:
 - Check if the uglify plugin can use ``keep_fnames``  for several packages / namespaces only. If you can do that, use ``keep_fnames`` for **@sensenet/default-content-types** only
 - You can hard-cast your type name to ``.typeIs(...)`` in the following way:
```ts
const query = new Query(q=>q.typeIs<Task>({name: "Task"} as typeof Task));
```
 - You can change the ``.typeIs(...)`` call with a  ``.term(..)`` segment. It will accept any string and use it as a query segment but it won't help you with type checking.

**Comment by LuisAverhoff** [comment]
Thanks for the reply, I think second possibilities would be probably be the best in terms of keeping everything compatible. It may be a little bit more verbose, but it is a small price to pay.
