### ISSUE TITLE
[BUG] Warnings and errors during unit test run

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#841]
## 📦 Package / Application

sn-client

## 🐜 Describe the bug

The mentioned warnings and errors appear during unit test run

## 👉 Steps To Reproduce

on develop branch run these commands:
```
yarn
yarn build
yarn test
```

- [x]  @sensenet/react-memoapp  examples/sn-react-memoapp/test/memo-panel.test.tsx (12.466 s)
`Material-UI: the ExpansionPanel component was renamed to Accordion to use a more common naming convention. 3X`

- [x]  PASS   @sensenet/document-viewer-react  packages/sn-document-viewer-react/test/DocumentViewer.test.tsx (15.345 s)

```
console.error
      Warning: `NaN` is an invalid value for the `top` css style property.
```

- [ ]  PASS   @sensenet/react-calendar  examples/sn-react-calendar/test/edit-dialog-body.test.tsx (7.792 s)     
```
 console.warn
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. 4X
```

- [x]  PASS   @sensenet/controls-react  packages/sn-controls-react/test/ReferenceGrid.test.tsx (6.023 s)
```
 console.error
      Warning: Each child in a list should have a unique "key" prop.
```

- [x]  PASS   @sensenet/hooks-react  packages/sn-hooks-react/test/use-session.test.tsx
`(node:23992) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'PageCount' of undefined`

- [x]  PASS   @sensenet/document-viewer-react  packages/sn-document-viewer-react/test/DocumentViewerRegeneratePreviews.test.tsx
`(node:23992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

- [ ]  PASS   @sensenet/hooks-react  packages/sn-hooks-react/test/load-settings.test.tsx   
`(node:3664) UnhandledPromiseRejectionWarning: Error: :(
`

- [ ]  PASS   @sensenet/client-core  packages/sn-client-core/test/allowed-child-types.test.ts
`(node:3664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)`

**Comment by taki9** [comment]
Quill errors are from the quill package, we can not fix them.
UnhandledPromiseRejectionWarning is not thrown when jest run that file only
