### ISSUE TITLE
[BUG] Name in the profile user dropdown

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#844]
# 🐜 Bug Report

The user dropdown on the userprofile shows the Name of the user instead of FirstName+LastName or LoginName

## 📦 Package / Application

snaas-profile

## 📃 Version

latest

## 👉 Steps To Reproduce

1. go to snaas-profile.test.sensenet.com
2. Login with info@sensenet.com

## 😯 Current behavior

![image](https://user-images.githubusercontent.com/6968860/92397407-12398700-f127-11ea-927c-73193a63dca4.png)

## 🤔 Expected behavior

User's FirstName+LastName should be shown and if they're not available it should fallback to LoginName

**Comment by pusztaienike** [comment]
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/61?_a=overview
