### ISSUE TITLE
[BUG] Double-clicking a Link content in the grid opens monaco editor

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#854]
# 🐜 Bug Report

Double clicking on a Link content opens monaco editor instead of the Edit view of the item.

## 📦 Package / Application

@sensenet/sn-app

## 📃 Version

latest

## 👉 Steps To Reproduce

1. Login to the admin ui
2. Go to the Content menu
3. Create a new LinkList or open an existing one
4. Create a Link into the LinkList
5. Double click the Link item in the grid

## 😯 Current behavior

Empty monaco editor is opened

## 🤔 Expected behavior

The edit view of the link content should be opened

## 🖼 Screenshots

![link_doubleclick](https://user-images.githubusercontent.com/6968860/92688724-21dee880-f33e-11ea-9179-79b799478059.gif)

**Comment by pusztaienike** [comment]
Cannot reproduce
