### ISSUE TITLE
Technical content types are visible in the ctd list

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#860]
Technical content types are visible in the ctd list which is noisy.

Content types should have an **IsSystemType flag** indicating whether it should be visible on the UI or not. Hiding or showing ctds is the **responsibility of the client**.

- Setting this flag on certain CTDs is part of this story (e.g. field setting content types)
- A UI switch (default OFF) on admin UI for showing system types is a **separate issue**.

![image](https://user-images.githubusercontent.com/6968860/92716999-db01ea80-f35f-11ea-8c24-b9450d5e0dee.png)

**Comment by tusmester** [comment]
We need to set this flag in the base package @kavics .
