### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Permission editor main page links

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#862]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that permission editor main screen links works as it is intended. 

![image](https://user-images.githubusercontent.com/22347393/92726611-228f7300-f36e-11ea-9718-b48168fdf457.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that permission editor displays the appropriate buttons.

## 🐾 Steps

1. Login with admin role
2. Click on Content menu item
3. Right click on "IT Workspace" in the tree
4. **Step:** Click 'Set permissions' dropdown item
    **Expected result:** Permission editor main page has two buttons (right-top) with the text of 'Make content pulic' and 'Assign new permission'
5. **Step:** Hover over 'Make content public' button
   **Expected result:** A tooltip has been appeared with the text of: "Clicking this button makes the content and the below sub-tree public for non-authenticated (Visitor) users"

# Test case 2

## 🧫 Purpose of the test

To ensure that permission editor 'Inherited from ancestor' children's link navigates to the permission editor screen of its parent.

## 🐾 Steps

1. Open inherited ancestor by clicking on its row
2. **Step:** Click on the (/Root/Content) link on Developers row
   **Expected result:** A new permission editor main page has been appeared with the title of 'Set permissions for Content'

![image](https://user-images.githubusercontent.com/22347393/92726727-55d20200-f36e-11ea-9a21-259cca3bbfd3.png)

**Comment by HeroicHitesh** [comment]
@herflis I would like to work on this. Right now I am setting up the project. Once it's done, will start working on the issue.

**Comment by herflis** [comment]
@HeroicHitesh I assigned the issue to you. Let us know if we can help you with anything
