### ISSUE TITLE
🧪 [E2E test] Add new permission entry

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#865]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._** 

# 🧪E2E test cases

The scope of these tests is to ensure that permission editor 'Assign new permission' button works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/92734577-f3caca00-f378-11ea-859e-b780b76c1136.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that 'Assign new permission' button opens a new dialog

## 🐾 Steps

1. Login with admin role
2. Click on Content menu item
3. Right click on "IT Workspace" in the tree
4. Click 'Set permissions' dropdown item
5. **Step:** Click on 'Assign new permission' button
   **Expected result:** New dialog should appears with an input field

![image](https://user-images.githubusercontent.com/22347393/92737090-25dd2b80-f37b-11ea-897c-3e1589db42a1.png)

# Test case 2

## 🧫 Purpose of the test

To ensure that selecting a new entry opens the permission editor dialog.

## 🐾 Steps

1. Type "Developer D" to the Name input field.
2. Select Developer Dog from the list

![image](https://user-images.githubusercontent.com/22347393/92735981-24f7ca00-f37a-11ea-91ad-c1df932d1b4a.png)

3. **Step:** Click on 'Add' button.
    **Expected result:** Devdog user should be in the 'Set on this content' list and new permission-editor dialog should open with the title of Developer Dog.

![image](https://user-images.githubusercontent.com/22347393/92736572-b0715b00-f37a-11ea-9d4d-79925b2a57b6.png)

4. **Step:** Click Cancel button
    **Expected result:** Dialog should close and Developer Dog user should disappears from the 'Set on this content' list.

**Comment by raihan71** [comment]
hey man, @pusztaienike can you assign this to me? I'd like to give a try

**Comment by pusztaienike** [comment]
> hey man, @pusztaienike can you assign this to me? I'd like to give a try

Thank you for participating in Hacktoberfest! You can find all the related info about sensenet hacktoberfest [here](https://hacktoberfest.sensenet.com/).  I strongly recommend you to check this [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) before you start. :) Good luck! 🏎️

**Comment by raihan71** [comment]
> > hey man, @pusztaienike can you assign this to me? I'd like to give a try
> 
> Thank you for participating in Hacktoberfest! You can find all the related info about sensenet hacktoberfest [here](https://hacktoberfest.sensenet.com/). I strongly recommend you to check this [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) before you start. :) Good luck! 🏎️

hey man, is there any easy test or simple test? this one seems difficult for me 😄 or maybe idk how to test it where I start

**Comment by pusztaienike** [comment]
> > > hey man, @pusztaienike can you assign this to me? I'd like to give a try
> > 
> > 
> > Thank you for participating in Hacktoberfest! You can find all the related info about sensenet hacktoberfest [here](https://hacktoberfest.sensenet.com/). I strongly recommend you to check this [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) before you start. :) Good luck! 🏎️
> 
> hey man, is there any easy test or simple test? this one seems difficult for me 😄 or maybe idk how to test it where I start

Hi @raihan71! I suggest you one from the followings:  
https://github.com/SenseNet/sn-client/issues/745
https://github.com/SenseNet/sn-client/issues/782
https://github.com/SenseNet/sn-client/issues/744

**Another tip:** If you are not familiar with cypress I recommend you to check the cypress docs site as well:
https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell

If you have any questions don't hesitate to contact us :)
