### ISSUE TITLE
[BUG]Apos bug

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#868]
# 🐜 Bug Report

apostrophe character not shown correctly with helper message at billing info

## 📦 Package / Application

profile

## 👉 Steps To Reproduce

1. Login 
2. Go to billing info
3. See helper messages

## 😯 Current behavior

Apos is encoded

## 🤔 Expected behavior

the message shows correctly

**Comment by pusztaienike** [comment]
https://github.com/SenseNet/sn-client/issues/851 it is duplicated
Here is the PR what contains the correction: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/63?_a=overview
