### ISSUE TITLE
[BUG]Contact us navigates to an other site

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#870]
# 🐜 Bug Report

Contact us button opens page in the same tab

## 📦 Package / Application

snaas-profile

## 📃 Version

latest

## 👉 Steps To Reproduce

1. go to profile
2. Login
3. Go to Edit Profile
4. Click on Contactus (sic!)

## 😯 Current behavior

navigates to sensenet.com

## 🤔 Expected behavior

open contact us either a popup or opens page in another tab

## 🌍 Your environment (for apps / examples)

- Device:
PC
- OS:
Windows 10
- Browser:
Edge 
- Version:
85.0.564.51

**Comment by pusztaienike** [comment]
PR: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-profile/pullrequest/64?_a=overview
