### ISSUE TITLE
[BUG] Invalid lifespan values on the "Edit" screen.

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#874]
# 🐜 Bug Report

Invalid lifespan values on the "Edit" screen.

## 📃 Version
latest

## 🐜 Describe the bug

On the edit screen there are 2 red fields:
- "Valid Till" message: "Date should not be before minimal date"
- "Valid From" message: "Date should not be before minimal date"

## 👉 Steps To Reproduce

- Login
- Navigate to "Content"
- Create a Folder
- Give "Folder name" and "Name"
- Submit
- Edit newly created folder

## 🤔 Expected behavior

1 - The field values should be valid OR
2 - These fields should be invisible if the "Enabled Lifespan" is off.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by tusmester** [comment]
Possibly related to #812
