### ISSUE TITLE
[BUG] Delete does not work.

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#876]
# 🐜 Bug Report

I deleted a folder successfully but after that, I cannot delete any content anyway. 

## 🐜 Describe the bug
Deleting one item, more items, click on the trash icon, select from the actions menu, etc. do not work.

## 👉 Steps To Reproduce

- Login.
- Navigate to Content.
- Create a folder.
- Create a second one.
- Select both newly created items.
- Try to delete them.
- If successfully deleted, please repeat once from the creation. I think the deletion will not work.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by tusmester** [comment]
Same here.
