### ISSUE TITLE
[BUG] Preview opening error

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#890]
# 🐜 Bug Report

I tried to generate preview for a .docx file. I wanted to open but I got error on the console and on the page as well:

![image](https://user-images.githubusercontent.com/22347393/93057118-b498c380-f66d-11ea-952d-e049a61c98a7.png)
![image](https://user-images.githubusercontent.com/22347393/93057141-bcf0fe80-f66d-11ea-95de-1a8e96e6c63d.png)

This file was working before. I could generate and open preview on same file.

## 📦 Package / Application

admin-ui

## 📃 Version

https://n5511pi5.sensenet.cloud

## 👉 Steps To Reproduce

1. Upload 
[d000.docx](https://github.com/SenseNet/sn-client/files/5216816/d000.docx) this file 
2. Double click on that

OR follow this link:

https://admin.sensenet.com/content/explorer/?path=%2FSampleWorkspace%2FDocument+library 

## 😯 Current behavior

Errors

## 🤔 Expected behavior

Prview should open

**Comment by herflis** [comment]
@pusztaienike I cannot reproduce this issue now with the attached file. Can you please check this again?

**Comment by pusztaienike** [comment]
It is working now 👍
