### ISSUE TITLE
[BUG] Cannot delete a localization file

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#892]
I created a new localization file for test purpose.I wanted to delete it but I couln't

## 📦 Package / Application

admin-ui

## 🐜 Describe the bug

There is no delete action in the context menu when I right-clicked the localization item.
![image](https://user-images.githubusercontent.com/22347393/93058948-56211480-f670-11ea-9546-054847746962.png)

Clicking on delete button on the keyboard is also not working for me

## 👉 Steps To Reproduce

1. Go to Localization menu
2. Right-click on an item
3. Search for delete option --> there is no delete option

## 😯 Current behavior

There is no delete option

## 🤔 Expected behavior

It should be

**Comment by herflis** [comment]
@tusmester I think it should be added to the base package
