### ISSUE TITLE
[BUG]reupload file says 500

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#900]
# 🐜 Bug Report

Upload a file already in the repository throws error

## 📦 Package / Application

admin-ui

## 📃 Version

latest

## 🐜 Describe the bug

Tried to upload a file to overwrite previous, but upload fails.

## 👉 Steps To Reproduce

1. Go to a folder
2. Click on upload
3. Browse a file already in the folder
4. try to upload

## 😯 Current behavior

Upload failed.
(one of the upload request says on the network tab: Cannot serve a binary field during uploading any stream.)

## 🤔 Expected behavior

upload successfully and the file is overwritten

## 🌍 Your environment (for apps / examples)

- Device:
PC
- OS:
Windows 10
- Browser:
Edge
- Version:
85.0.564.51

**Comment by tusmester** [comment]
I think this is not the case anymore.
Current behavior: **a new file is created** every time I upload the same document. Is this correct? The `Upload` action is sent with `overwrite: false`.

**Comment by herflis** [comment]
@VargaJoe I cannot reproduce this issue either, because of the overwrite: false mentioned by @tusmester. Maybe it is an issue with the file itself (may not be fully uploaded or it became corrupt, etc) Can you please share the file that caused this issue?

**Comment by VargaJoe** [comment]
tested again with different file types:
- docx and pdf file throws error on reupload
- xslsx, xls, txt, rtf, doc, csv successfully reuploaded
![image](https://user-images.githubusercontent.com/17780970/95055227-46d33b00-06f3-11eb-9b47-59509797696b.png)

**Comment by VargaJoe** [comment]
I've tested multiple times:
- when upload files, and reupload again, uploads throw error
- when upload files, and refresh folder, try to reupload again, then new numbered files've been created, but some files throws error (docx and pdf files usually)

Can be reproduce with netcore test.

**Comment by herflis** [comment]
I can reproduce this issue as well.

steps:
1. login to netcore.test.sensenet.com at admin.test.sensenet.com
2. Go to Sample workspace's doclib, upload a file
3. Upload the same same file again

![image](https://user-images.githubusercontent.com/6968860/97848275-221db380-1cf1-11eb-861e-644c799ff515.png)

**Comment by kavics** [comment]
The blob is not finalized after the last byte is uploaded. Therefore the currently uploaded blob stays in the "staged" state that causes this error: `Cannot serve a binary field during uploading any stream.`. There is explicit action(s) that removes the uploaded blob from this state.
