### ISSUE TITLE
[BUG]image ctd displayname is weird

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#902]
# 🐜 Bug Report

Image type has displayname: 
Ctd-Imageen-USName-DisplayName

## 📦 Package / Application

admin-ui

## 📃 Version

latest

## 🐜 Describe the bug

DisplayName of Image type does not have resource

## 👉 Steps To Reproduce

1. Click Add new action
2. Marvel on the Image element

## 😯 Current behavior

Ctd-Imageen-USName-DisplayName

## 🤔 Expected behavior

Image

**Comment by pusztaienike** [comment]
PR: https://github.com/SenseNet/sensenet/pull/1095
