### ISSUE TITLE
[BUG]Workspace ctd name is weird

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sn-client#903]
# 🐜 Bug Report

Workspace type has name: 
Ctd-Workspaceen-USName-DisplayName

## 📦 Package / Application

admin-ui

## 📃 Version

latest

## 🐜 Describe the bug

Name of Workspace type does not have resource

## 👉 Steps To Reproduce

1. Click Add new action
2. Select Workspace
3. Be shocked by Name input

## 😯 Current behavior

Ctd-Workspaceen-USName-DisplayName

## 🤔 Expected behavior

Workspace

**Comment by pusztaienike** [comment]
Duplicates of https://github.com/SenseNet/sn-client/issues/889
