### ISSUE TITLE
[BUG] Cannot move doc to Doclib

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#905]
Failed to move content c000.docx to MyDocs Cannot move /Root/Content/c000.docx (Image) to /Root/Content/MyDocs (DocumentLibrary) because 'Image' type is not allowed in the new position.

# 🐜 Bug Report

I have created a Document Library under Content and upload a .docx file. I could not move the docx under the Document Library cause it has no AllowedchildType wiith the name of 'Image'

## 📦 Package / Application

admin-ui

## 👉 Steps To Reproduce

1. Login
2. Navigate to Content
3. Create a DocumentLibrary: "MyDocs" (AllowedChildType should be File only)
4. Go to Content
5. Upload here a .docx file
6. Move the .docx file into the "MyDocs"

## 😯 Current behavior

Failed to move content c000.docx to MyDocs Cannot move /Root/Content/c000.docx (Image) to /Root/Content/MyDocs (DocumentLibrary) because 'Image' type is not allowed in the new position.

## 🤔 Expected behavior

Move should be successful cause I can upload the same .docx file under MyDocs

## 🖼 Screenshots

![move_is_not_working](https://user-images.githubusercontent.com/22347393/93197690-3c54ff80-f74c-11ea-9e0a-a64faf4b743b.gif)

I could move the content after adding Image to MyDocs's allowedChildTypes but it is confusing if move action is disabled but upload is not.

**Comment by herflis** [comment]
Content cannot be copied or moved because of the PreviewImages. We should handle this typecheck on the backend and let the user copy or move PreviewImages along with the content without setting Image or PreviewImage as an allowed childtype
