### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Users

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#907]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that Users tab in Users and groups menu works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/93210284-9d3a0300-f75f-11ea-97a1-626a9e21723d.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that users list has the appropriate data.

## 🐾 Steps

1. Login with admin role
2. **Step:** Click on Users and Groups menu item
    **Expected result:** The users table has the following contents with the following columns:

Contents:
- Business Cat
- Developer Dog

Columns: 
- DisplayName
- Email
- AllRoles
- Enabled
- Actions

# Test case 2

## 🧫 Purpose of the test

To ensure that right click on a user opens context-menu

## 🐾 Steps

1. **Step:** Right click on Developer Dog
**Expected result:** The context-menu dropdown should be visible with the following actions:

- Browse
- Copy to
- Edit
- Move to
- Versions
- Share (Disabled)
- Delete
- Set permissions

2. Click away

# Test case 3

## 🧫 Purpose of the test

Double click on user should open a edit form of the content.

## 🐾 Steps

1. **Step:** Double click on Developer Dog
**Expected result:** Edit form of the user has opened with the title of 'Edit Developer Dog'

![image](https://user-images.githubusercontent.com/22347393/94692117-74eefe80-0332-11eb-8841-ba582a85bcac.png)

2. Click Cancel button

**Comment by ashutosh97** [comment]
I would like to work on this.
