### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Groups

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#908]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that Groups tab in Users and groups menu works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/93212535-01aa9180-f763-11ea-9deb-cffaa11a43a5.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that groups list has the appropriate data.

## 🐾 Steps

1. Login with admin role
2. Click on Users and Groups menu item
3. **Step:** Switch to groups tab
    **Expected result:** The groups table has the following contents with the following columns:

Contents:

- Administrators
- Developers
- Editors

Columns:

- DisplayName
- Description
- Members
- Actions

# Test case 2

## 🧫 Purpose of the test

To ensure that right click on a group opens context-menu

## 🐾 Steps

1. **Step:** Right click on Editors group
    **Expected result:** The context-menu dropdown should be visible with the following actions:

- Browse
- Copy to
- Edit
- Move to
- Versions
- Share (Disabled)
- Delete
- Set permissions

2. Click away

# Test case 3

## 🧫 Purpose of the test

Double click on group should open a edit form of the content.

## 🐾 Steps

1. **Step:** Double click on Editors
    **Expected result:** Edit form of the group has opened with the title of 'Edit Editors'

![image](https://user-images.githubusercontent.com/22347393/93213141-c492cf00-f763-11ea-951b-0437134688a6.png)

**Comment by NileshPatel17** [comment]
@herflis please assign it to me.
