### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Header & Dashboard

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#911]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the header and the dashboard work as it is intended.

![image](https://user-images.githubusercontent.com/22347393/93218322-5ef61100-f76a-11ea-83ed-fa0ea8628c65.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that the header contains the url of the current repository.

## 🐾 Steps

1. **Step:** Login with admin role
    **Expected result:** "https://dev.demo.sensenet.com" should be visible on the header

![image](https://user-images.githubusercontent.com/22347393/93218496-949afa00-f76a-11ea-9b67-b42f280ee9af.png)

# Test case 2

## 🧫 Purpose of the test

To ensure that the dashboard has correct subscription plan info.

## 🐾 Steps

1. **Step:** Click on the sensenet icon in the header
    **Expected result:** Dashboard should open with the title of "Welcome to your Dev Demo project"

![image](https://user-images.githubusercontent.com/22347393/93218724-d2981e00-f76a-11ea-83b4-721a675f0a97.png)

2. **Step:** Check the Your subscription plan section of the dashboard:
   **Expected result:** This section should contain the Developer plan text and features list should be the following:

- 3 users
- 500 content
- 1 GB storage space

# Test case 3

## 🧫 Purpose of the test

To ensure that the dashboard has correct usage info.

## 🐾 Steps

1. **Step:** Check the Current usage section of the dashboard:
   **Expected result:** 
Users should be x of 3 where x <= 3
Content should be y of 500 where y <= 500
Storage space should be z of 1 GB where z <= 1

![image](https://user-images.githubusercontent.com/22347393/93219309-7f729b00-f76b-11ea-837d-294472e34861.png)

**Comment by NileshPatel17** [comment]
created PR. please let me know if this can be merged.
