### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Edit content

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#916]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that content modification works as it is intended.

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure edit content works properly.

## 🐾 Steps

1. Login with admin role
2. Click on Content menu item
3. Right click on IT Workspace
4. Select Edit from the list

![image](https://user-images.githubusercontent.com/22347393/93334147-b658b780-f824-11ea-8b5d-e19ca952df3f.png)

5. Change Display name field to IT Workspace Test

![image](https://user-images.githubusercontent.com/22347393/93334201-d5574980-f824-11ea-99f3-aada5889d079.png)

6. **Step:** Click on Submit button
    **Expected result:** IT workspace changed to IT Workspace Test in the tree and in the breadcrumb as well.

![image](https://user-images.githubusercontent.com/22347393/93334290-ff107080-f824-11ea-808a-c49f5f0b0f5a.png)

# Test case 2

## 🧫 Purpose of the test

To ensure edit content works properly.

## 🐾 Steps

1. Right click on IT Workspace
2. Select Edit from the list
3. Change Display name field back to IT Workspace
4. **Step:** Click on Submit button
    **Expected result:** IT workspace Test changed back to IT Workspace in the tree and in the breadcrumb as well.

**Comment by NileshPatel17** [comment]
@herflis please assign it to me.
