### ISSUE TITLE
[BUG] Cannot update built-in localization file

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#918]
# 🐜 Bug Report

As a member of the public adminstrators group I should be able to open and save resource files but I cannot

## 📃 Version

latest

## 🐜 Describe the bug

Public administrators and developers can only update localization files which are created by them

## 👉 Steps To Reproduce

1. Login to a repo with businesscat
2. Go to Localizations
3. Open a resource file from the built-in ones
4. Change something in the file and hit the save button

## 😯 Current behavior

User gets an error that he is not accessed to save the content.

## 🤔 Expected behavior

public admins and devs should be able to save a built-in localization fie

**Comment by pusztaienike** [comment]
Maybe this PR will solve it: https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-services/pullrequest/80?_a=overview
