### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Saved queries

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#935]
**_Before you start working on an issue please take a look at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._** 

# 🧪E2E test cases

The scope of these tests is to ensure that saved queries works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/94119454-3a2b2900-fe4f-11ea-8eca-369a448f1ff1.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that saving a query is working properly

## 🐾 Steps

1. Login with admin role
2. Click on Search menu item
3. Click on 'Add new' button
4. **Step:** Type `+InFolder:'/Root/Content/IT/Document_Library'` to search input
    **Expected result:** Chicago and Munich should be in list under search input

![image](https://user-images.githubusercontent.com/22347393/94118056-47471880-fe4d-11ea-91c1-a843958b2826.png)

5. Click on 'Save query' button
6. Type `test query for IT Doclib` to the input field

![image](https://user-images.githubusercontent.com/22347393/94118202-7bbad480-fe4d-11ea-974d-4eb017634f9f.png)

7. Click on Save button
8. **Step:** Click on Search menu item
    **Expected result:** `test query for IT Doclib` should be in the list od saved queries

![image](https://user-images.githubusercontent.com/22347393/94118346-b7559e80-fe4d-11ea-8dd4-1f5947b26e1e.png)

9. **Step:** Double click on `test query for IT Doclib`
    **Expected result:** Input field should contain: `+InFolder:'/Root/Content/IT/Document_Library'` text and list should contain Chicago and Munich items

![image](https://user-images.githubusercontent.com/22347393/94118585-0bf91980-fe4e-11ea-930e-1d98783dab07.png)

# Test case 2

## 🧫 Purpose of the test

To ensure that delete of a saved query works properly.

## 🐾 Steps

1. Click on Search menuitem
2. Rigth click on `test query for IT Doclib` item
3. Select Delete from the dropdown list
4. Tick permanently
5. **Step:** Click on Delete button
    **Expected result:** `There is no query saved yet.` text should be in the list, (and `test query for IT Doclib` is not there in the list)

**Comment by NileshPatel17** [comment]
@herflis can you please assign to me?

**Comment by pusztaienike** [comment]
> @herflis can you please assign to me?

@NileshPatel17   I have assigned it to you :)
