### ISSUE TITLE
[BUG] Copy of files from one workspace to another doesn't work

### ISSUE THREAD

**Issue by molnarm84** [SenseNet/sn-client#955]
# 🐜 Bug Report

Want to copy file (single and batch) from one workspace to another but it doesn't work.

## 🐜 Describe the bug

I have tried to copy file from one workspace toa nother in my repository but it gives error message.

## 😯 Current behavior

 I see the following error message:
'Failed to copy content EULA v1.docx to Document library.'

## 🤔 Expected behavior

Copied file should appear in the destination folder (Sample workspace/ Document Library)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by pusztaienike** [comment]
I could not reproduce the exact case, but I also could not copy a file from a Workspace/Doc_Lib to Another_Ws/Another_Doclib but the error message was:
`Cannot copy a list item into an another list.`
Is this error valid here @tusmester ?
