### ISSUE TITLE
🧪 [E2E test] Add Cypress test - Task list

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#960]
# 🧪E2E test cases

The scope of these tests is to ensure that task list creation, modification, and delete works as it is intended.

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

To ensure that task list creation works properly.

## 🐾 Steps

1. Login with admin role
2. Click on Content menuitem
3. Click on IT Workspace in the tree
4. Click on 'Add new' button
5. Select Task List from the dropdown list
6. Fill the form with the following data:
- Name: Test Task List
- DisplayName: Test Task List
7. **Step:** Click on submit button
    **Expected result:** Test Task List should be in the list

![image](https://user-images.githubusercontent.com/22347393/94264859-cd3f8e00-ff37-11ea-88b2-1a059b74b3d1.png)

8. Click on Test Task List in the tree
9. **Step:** Click on 'Add new button'
**Expected result:** The dropdown should contain the following item:

- Task 

![image](https://user-images.githubusercontent.com/22347393/94264883-daf51380-ff37-11ea-83c0-8486727f3f1c.png)

10. Click away

# Test case 2

## 🧫 Purpose of the test

To ensure that modifying a task list content works properly

## 🐾 Steps

1. Click on IT Workspace in the tree
2. Right click on Test Task List
3. Select Edit from the dropdown list
4. Change the DisplayName from Test Task List to Changed Test Task List
5. **Step:** Click on submit button
    **Expected result:** Changed Test Task List should be in the list, Test Task List should not be

![image](https://user-images.githubusercontent.com/22347393/94264954-f7914b80-ff37-11ea-8151-78058fc09908.png)

# Test case 3

## 🧫 Purpose of the test

To ensure that delete a task list content works properly

## 🐾 Steps

1. Right click on Changed Test Task List
2. Select Delete from the dropdown list
3. Tick permanently
4. **Step:** Click on Delete button
    **Expected result:** Changed Test Task List should not be in the list

**Comment by NileshPatel17** [comment]
I am interested to take up e2e issues. but i am unable to reproduce the issue..
following are the steps i followed:-
1. run command: `yarn start:dms:e2e` snd login with 'businesscat' account.
![Uploading Screenshot 2020-10-12 at 6.24.20 PM.png…]()
2. post login, clicking on "it workspace" or "content", nothing happens.
<img width="1440" alt="Screenshot 2020-10-12 at 6 28 36 PM" src="https://user-images.githubusercontent.com/27020381/95749139-c09d9280-0cb8-11eb-91d4-c80f38382399.png">

**Comment by herflis** [comment]
Hi @NileshPatel17 these tests are related to the admin surface, but you've started the dms app :) I suggest you to check the [contribution guide](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md), and also read the info on our [hacktoberfest site](https://hacktoberfest.sensenet.com/) if you hadn't already, these will help you with the first steps :) btw I assign the issue to you. Feel free to ask if we can help you!

**Comment by NileshPatel17** [comment]
Allright.. got it..

where do i get client secret??
<img width="581" alt="Screenshot 2020-10-13 at 6 53 51 PM" src="https://user-images.githubusercontent.com/27020381/95866359-759d8100-0d85-11eb-850c-877bbcc0ef09.png">

**Comment by NileshPatel17** [comment]
Also observed upon login, some of the api are failing. It was working yesterday.
<img width="1440" alt="Screenshot 2020-10-13 at 7 10 35 PM" src="https://user-images.githubusercontent.com/27020381/95868392-c7dfa180-0d87-11eb-956c-624834792c80.png">

**Comment by NileshPatel17** [comment]
@herflis sorry to bother you
steps i followed:-

1. running `yarn start` to the dir => sn-client/apps/sensenet
2. visit localhost:8080 and login with ‘businesscat’ account
3. I do not see profile page upon clicking on “avatar”

**Comment by NileshPatel17** [comment]
sent an request.. once its approved, i should be able to see api keys
<img width="1168" alt="Screenshot 2020-10-13 at 10 21 17 PM" src="https://user-images.githubusercontent.com/27020381/95891393-a5a74d00-0da2-11eb-81b2-7b6f6ecfe21b.png">

**Comment by NileshPatel17** [comment]
why i am unable to login with my repository??

<img width="1440" alt="Screenshot 2020-10-14 at 8 05 07 AM" src="https://user-images.githubusercontent.com/27020381/95936781-0448e700-0df4-11eb-80e2-274efc71b417.png">

here is my repository.
<img width="1440" alt="Screenshot 2020-10-14 at 8 06 34 AM" src="https://user-images.githubusercontent.com/27020381/95936879-335f5880-0df4-11eb-961c-1634a8fa063e.png">

**Comment by herflis** [comment]
@NileshPatel17 you have to put 'https://' as well

**Comment by NileshPatel17** [comment]
@herflis altight.. i am almost there.. only thing is to configure identity server. what should be?
`"identityServer": "https://is.demo.sensenet.com",`

**Comment by herflis** [comment]
![image](https://user-images.githubusercontent.com/6968860/95979316-bcd65100-0e1b-11eb-8dc0-f37078cb16e2.png)

**Comment by NileshPatel17** [comment]
I have written test case to add new item successfully . now how i would test if newly added item is present in grid?
<img width="1440" alt="Screenshot 2020-10-18 at 9 15 12 AM" src="https://user-images.githubusercontent.com/27020381/96358235-8b62cb80-1122-11eb-8857-7a2e57d96ebc.png">

**Comment by herflis** [comment]
Hi @NileshPatel17 would you like to make a pr for this issue as well, or may I unassigne this? :)

**Comment by NileshPatel17** [comment]
@herflis Please allow me to work on this. Its almost 90% completed.
