### ISSUE TITLE
[BUG] Cannot edit some CTDs

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#988]
In some cases double click on CTD item makes the edit-view open instead of the binary editor. 
Eg.: Resource with businesscat user (bultin/admin can open in the binary editor)

## 📦 Package / Application

admin-ui

## 👉 Steps To Reproduce

1. Login with businesscat
2. Go to Content Types menu
3. Open Resource

## 😯 Current behavior

edit-view has opened

## 🤔 Expected behavior

binary-editor should open (or if there is no permission - nothing)

## 🖼 Screenshots

![cannot_edit_resource](https://user-images.githubusercontent.com/22347393/94810230-0bcfbf80-03f4-11eb-82a9-62da355a0bc1.gif)

**Comment by herflis** [comment]
This issue brought up a bigger problem, that will be solved on the backend [https://github.com/SenseNet/sensenet/issues/1383](https://github.com/SenseNet/sensenet/issues/1383)
