### ISSUE TITLE
[BUG] Upload indicator covers filename

### ISSUE THREAD

**Issue by pfaffr** [SenseNet/sn-client#996]
# 🐜 Bug Report

Upload indicator covers the filename

## 👉 Steps To Reproduce

1. Go Manage users and groups...
2. Choose one user
3. Click Edit in the context menu
4. Click Add or Change Avatar
5. Drag and drop a pic into the pop-up than press Upload

The appearing Upload indicator bar covers the filename. It is not nice.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/37662938/94919311-97108a00-04b4-11eb-8d5e-3c737ec86524.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: PC
- OS: Windows
- Browser: Chrome
- Version: 85.0.4183.83

**Comment by herflis** [comment]
@pfaffr thanks for reporting this issue, we are fully redesigning the upload feature and the related ui in q4, so now I close this issue
